### ISSUE TITLE
استفاده از تقویم در کامپوز

### ISSUE THREAD

**Issue by Borderliner** [persian-calendar/persian-calendar#1009]
با سلام و خسته نباشید.

میخواستم از این تقویم توی یه برنامه کامپوز استفاده کنم. داخل سورس برنامه فایل های مربوط به کامپوز رو دیدم ولی اطلاعاتی راجع به اینکه چطور میتونم تقویم رو وارد یه پروژه کامپوز کنم پیدا نکردم. ممنون میشم اگه کسی میدونه بهم بگه.

**Comment by ebraminio** [comment]
سلام گرامی این مخزن بیشتر حالت برنامه‌ای دارد و در حالت کتابخانه‌ای خصوصاً به خاطر مجوزی سورس برنامه چندان کاربردی ندارد و قسمت‌های کامپوز برنامه بیشتر قسمت‌های گوشه‌ای برنامه است که از آنجایی که هنوز پشتیبانی از اندروید ۴ را داریم در حالت انتشار عمومی برنامه نیست :/ ولی آنچه که می‌گویید شاید در آینده ممکن باشد که قسمت‌های مختلف برنامه بعد از جدا شدن از سورس اصلی برنامه قابل استفاده در کتابخانه‌های دیگر نیز باشد، ممنون :)

**Comment by Borderliner** [comment]
من تونستم با کمی تغییرات توی build.gradle فولدر PersianCalendar رو به برنامه اضافه کنم، تبدیلش کنم به library و ایمپورتش کنم. توی اکتیویتی اصلی هم init میکنم اما صفحه خالیه و چیزی نشون نمیده.
تقویم فارسی به کامپوز سراغ ندارید؟

**Comment by ebraminio** [comment]
واقعیت جی‌پی‌ال به‌گونه‌ای هم به شکل https://en.wikipedia.org/wiki/Viral_license عمل می‌کند به خاطر همین کمی برای کتابخانه شدن شاید مناسب نباشد و از آنجایی که ما هم از چیزهایی با این مجوز استفاده کرده‌ایم توان تغییر مجوز را نداریم :/

یکی از دوستانی که در این پروژه نقش بزرگی داشتند نسخهٔ کامپوزی از جدول تقویم برای برنامهٔ خود طراحی کرده‌اند ولی تاجایی که می‌دانم اوپن‌سورس نیست و فکر می‌کنم کتابخانه‌های بسیار مفصل‌تر و پیشرفته‌تر از نظر امکانات برای تقویم میلادی در کامپوز یا ویو عادی دیده باشم

**Comment by Borderliner** [comment]
متوجهم. ناچارن به [https://github.com/hi-manshu/Kalendar](Kalendar) متوسل شدم تا ببینیم چی میشه. :)

**Comment by ebraminio** [comment]
به نظر که زیباست، ممنون بابت معرفی 🙏
