### ISSUE TITLE
Wrong Sunset And Sunrise

### ISSUE THREAD

**Issue by RazaDroid** [persian-calendar/persian-calendar#1011]
I'm in Osh City Kyrgyzstan and App is Showing is same
But the sunrise and sunset time showing wrong

**Comment by ebraminio** [comment]
Hi! First of all, it's just fantastic to see that this app has brought your attention, we even love to see it to be translated to your language if you are interested, about the particular issue can you share more details and screenshots on what has went wrong? How many minutes or hours it's wrong, and have you tried to change the pray time algorithm if that improves the situation? Thanks!

**Comment by RazaDroid** [comment]
> we even love to see it to be translated to your language if you are interested

I'm from India and it's Already Available Urdu Translation

>the particular issue can you share more details and screenshots on what has went wrong

I'm sharing screenshot
![Screenshot_20221217-144015](https://user-images.githubusercontent.com/37952910/208233795-dd596d24-4a71-4bb4-9d13-d814bf8de18a.png)
![Screenshot_20221217-144023](https://user-images.githubusercontent.com/37952910/208233801-b2915c1a-eb01-4caf-ada1-823e91f1af61.png)


It's today sunrise and sunset time
![Screenshot_20221217-144116](https://user-images.githubusercontent.com/37952910/208233826-f334bdfa-a5a0-414f-af03-d850de1106a2.png)


And I'm using other app like divinepearls and shia companion , in that app showing correct time
![Screenshot_20221217-144032](https://user-images.githubusercontent.com/37952910/208233904-1a006a66-c3c1-4812-a25a-6c203750243a.png)
