### ISSUE TITLE
Allow setting bg color for widget separately for Light/Dark mode 

### ISSUE THREAD

**Issue by mrmotallebi** [persian-calendar/persian-calendar#1012]
On Samsung device / Android 12 / OneUI 5

For widget's background color, choosing the option to follow the system color basically sets the color based on the theme (for example blue).
This does change automatically with Light/Dark mode, but ideally I would like to set a separate color for Light and Dark modes that would automatically switch between them. For example, transparent white for day and transparent black for night. See attached screenshot of Samsung's Reminder widget as an example.

A very cool and handy app overall. Thanks.

![Screenshot_20221220_081803_One UI Home](https://user-images.githubusercontent.com/4098638/208678046-fb19024f-789b-49cc-ba52-587d3e1191f1.jpg)
![Screenshot_20221220_081851_One UI Home](https://user-images.githubusercontent.com/4098638/208678047-753ac0e0-54eb-4489-8bc7-cd94274706bc.jpg)
![Screenshot_20221220_080902_One UI Home](https://user-images.githubusercontent.com/4098638/208678049-245db4e3-2d42-4352-b22e-96467ac0591e.jpg)
![Screenshot_20221220_080837_One UI Home](https://user-images.githubusercontent.com/4098638/208678048-1499cd99-66df-4700-9564-ff70a5196225.jpg)

**Comment by ebraminio** [comment]
سلام گرامی گزینهٔ جالبی است ولی به نظر کمی افزودن تنظیمی دیگر فقط برای حالت تاریک یا روشن تنظیمات را پیچیده‌تر می‌کند، به نظرم ببینیم کدام ویجت‌ها، خصوصاً ویجت‌های برنامه‌های گوگلی از رنگ‌بندی سیستمی پیروی کرده و با قرار دادن آن ویجت به‌عنوان الگو، رنگ پیش‌زمینه ویجت را برای همهٔ کاربران بدون افزودن تنظیمی جدید بهبود دهیم، رنگ‌بندی فعلی به گونه‌ای شبیه‌تر به برنامهٔ ساعت گوگل بوده ولی شاید بتوان برنامهٔ تقویم را بیشتر پیروی کرد،

<img width="478" alt="image" src="https://user-images.githubusercontent.com/833473/208828500-0bb3ae63-43cb-4b0b-9758-f53818f9a05e.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/833473/208828660-e1bd76bb-496f-4ae7-8bdd-63918c1851aa.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/833473/208828544-72cca03f-c6c5-4305-8e45-b49b17141d32.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/833473/208828593-9f736bae-508c-4432-bfab-e3fd897abd2e.png">

**Comment by mrmotallebi** [comment]
Fair response. Thanks a lot.
