### ISSUE TITLE
امکان تغییر مبدا تاریخ

### ISSUE THREAD

**Issue by Sahand395** [persian-calendar/persian-calendar#1018]
با سلام و سپاس از تیم سازنده برنامه
متاسفانه تنها ایراد برنامه برای من این است که مبدا تاریخ هجرت و جابجایی یک عرب از شهری به شهر دیگر (سال ۱۴۰۱ شمسی) و غیر قابل تغییر است، سالنامه قبلی که داشتم (سالنامه آریایی) امکان تغییر مبدا تاریخ رو قرار داده بود (زرتشتی،میترایی، آریایی و از همه مهم تر شاهنشاهی)
چناچه انجام این تغییر با سیاست های شما مغایرت داشته و نمی توانید این امکان را اضافه کنید با اجازه شما خودم یه فورک از برنامه با این تغییر ایجاد و منتشر خواهم کرد

**Comment by ebraminio** [comment]
سلام گرامی، بله سعی در این برنامه ارائه مواردی است که بتوان منبع رسمی برای آن داشت چرا که از آنجایی که پروژه اوپن‌سورس و چند نفره است، تنها راه پرهیز از تصمیم‌های درون پروژه‌ای تا جای ممکن و امکان ارجاع به منابع بیرونی و رسمی است به خاطر همین برای این موارد یا پیشنهاد افزودن یا کاهش مناسبت‌ها بهترین راه مطرح کردن با مرکز تقویم دانشگاه تهران خواهد بود، ممنونم 😊
