### ISSUE TITLE
Wrong theme colors

### ISSUE THREAD

**Issue by imto1** [persian-calendar/persian-calendar#1031]
Color of holidays are nearly the same as other days and the difference between the colors are barely visible when app theme is set to **system default** in settings.
I'm using Persian Calendar 7.8.0 F-Droid version on Nokia 6.1 with LineageOS 20.0(Android 13) and phone them is dark.
![Screenshot_20230204-142232_Persian Calendar.png](https://user-images.githubusercontent.com/43239919/216764713-af17f782-9987-4f5c-8be8-41f13a7d4d78.png)

**Comment by imto1** [comment]
گویا قبلا اعلام شده. چون از درون برنامه گزارش کردم. قبل از ایجاد گزارش متوجه تکراری‌ بودن اون نشدم.
پوزش 🙏🏻

**Comment by ebraminio** [comment]
@imto1 
درست می‌فرمایید گرامی ولی راه‌حلی هم به ذهنم نرسیده :/ مثلاً با سبز بودن رنگ اینگونه می‌شود:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/833473/216773919-4ee61d25-51fa-49f2-97b0-08b3651a2563.png">

ولی ظاهراً در بعضی رنگ‌های پویا خوب نمی‌شود :/

**Comment by ebraminio** [comment]
و البته می‌شود پوستهٔ غیر پویا را تنظیم کرد، راه‌حل خوبی نیست ولی شاید از وضع فعلی بهتر باشد
