### ISSUE TITLE
اندازهٔ آیکن اعلان

### ISSUE THREAD

**Issue by amirrezaamirisej** [persian-calendar/persian-calendar#1032]
با سلام و عرض تشکر.
پیشنهاد دارم آیکن اعلان کمی درشت‌تر یا بولد باشد. مثلاً هم‌اندازهٔ فونت ساعت دستگاه.
![Screenshot_20230207-183326_Chrome](https://user-images.githubusercontent.com/112181423/217283490-3ea45e14-2576-4341-9f90-ea7ad9ea8ced.jpg)

**Comment by ebraminio** [comment]
سلام گرامی امکان بزرگتر شدن ندارد متأسفانه

https://github.com/persian-calendar/persian-calendar/blob/main/PersianCalendar/src/main/res/drawable/day28_ar.png

و همین الآن عرض ممکن را پر کرده :/

**Comment by amirrezaamirisej** [comment]
عه پس باشه :)
بازم دمتون گرم. ❤

**Comment by ebraminio** [comment]
🙏😊
