### ISSUE TITLE
رنگ روزهای تعطیلی

### ISSUE THREAD

**Issue by CryptoSaul** [persian-calendar/persian-calendar#1039]
![Screenshot_2023-03-02-10-08-43-681_com byagowi persiancalendar](https://user-images.githubusercontent.com/13509695/222350740-4085137e-4ac5-44ee-bf8c-0991363ff260.jpg)
رنگ روزهای تعطیلی در miui 14 درست نشون داده نمیشه و کنتراست کمی داره

**Comment by SaeidArya** [comment]
من هم این مشکل رو با تم‌های تیره دارم
وان‌پلاس ۱۰ پرو؛ اندروید ۱۳
![Screenshot_2023-04-13-15-02-36-40_8c311b1fa2b9de008bf2d517a214ee21~01](https://user-images.githubusercontent.com/19968220/231746390-745509b0-a84e-4a36-99bb-97f059ef59df.jpg)
