### ISSUE TITLE
ساعت تحویل سال

### ISSUE THREAD

**Issue by arabacc2** [persian-calendar/persian-calendar#1046]
زمان تحویل سال 1402 اشتباه درج شده است بجای 12/54بعد ظهر(ب.ظ) .قبل ظهر (ق.ظ)

**Comment by ebraminio** [comment]
سلام گرامی در نسخهٔ ۷.۹.۰ از بامداد استفاده شده است لطفاً بررسی فرمایید، ممنون 😊
