### ISSUE TITLE
 پخش اذان یکساعت بعد از وقت

### ISSUE THREAD

**Issue by martyr72** [persian-calendar/persian-calendar#1049]
به نام خدا
سلام. با آنکه ساعت گوشی بصورت دستی یکساعت به عقب برده شده و با ساعت رسمی همزمان شده است، ولی اذان  یکساعت بعد یعنی همزمان با ساعت تابستانی که اکنون  منتفی شده است، پخش می‌شود 
@alirezaafkar 
@ebraminio

**Comment by mskf1383** [comment]
الان دیدم که یه انتشار جدید موجوده که مشکل رو حل کرده
ان شاء اللّٰه زودتر به اف‌دروید هم بیاد

**Comment by ebraminio** [comment]
برای نسخهٔ جدید به f-droid هم پیام دادم https://gitlab.com/fdroid/fdroiddata/-/issues/2939 ولی فکر کنم مشکل تأخیر اذان حتی با به‌روزرسانی برطرف نشود :/

**Comment by ebraminio** [comment]
احتمالاً در نسخهٔ v7.9.5 که apk آن را اینجا هم قرار دارد https://github.com/persian-calendar/persian-calendar/releases/tag/v7.9.5 احتمالاً مشکل برطرف شود، ممنون 😊

**Comment by martyr72** [comment]
نسخه جدید رو نصب کردم
برای بررسی رفع اشکال باید تا سحر منتظر بمونم
سرعت عمل و تعهد در پاسخگویی، بسیار بی‌نظیر و قابل تقدیر است

**Comment by ebraminio** [comment]
بله آزمایش آن بسیار مهم و خوب خواهد بود که بتوانم فردا انتشار را عمومی کنم، ممنونم گرامی 😊

**Comment by martyr72** [comment]
سلام. روزه‌ها و عبادات شما قبول حق تعالی
در بروز سانی حدید، مشکل اذان برطرف شد و اذان صبح بموقع پخش شد
موفق و پیروز باشید

**Comment by ebraminio** [comment]
عالی شد ممنونم گرامی 😊

**Comment by ebraminio** [comment]
در نسخهٔ ۷.۹.۰ خصوصاً در گوشی‌هایی ساعت دستی عقب برده نشده بود برنامه کار می‌کرد و این چیزی نیست که ظاهراً کاربران مایل به آن باشند، دربارهٔ کشورهای دیگر تغییری نخواهد داشت، کد مربوط به آن اینجاست https://github.com/persian-calendar/persian-calendar/blob/104a31168cf31c9a1baa34becd1d001719a3990a/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/utils/Utils.kt#L33-L36 ممنون 😊
