### ISSUE TITLE
there is about half a year that F-droid builds won't get updates

### ISSUE THREAD

**Issue by 0xRustlang** [persian-calendar/persian-calendar#1050]
سلام
حدود شش ماهه که آپدیتها در اف دروید کامپایل نمیشن

نمیدونم مشکل از فیل شدن کامپایلر اف دروید هست یا از کجاست ولی میشه بررسی کنید و در صورت امکان برطرفش کنید؟

برای گوشی های بدون پلی سرویس مثل هواوی یا کاستوم رام اف دروید گزینه بسیار بهتری از گوگل پلی هست برای راحت بودن آپدیت کردن برنامه نسبت به آپدیت از گیت هاب و یا استفاده از سایت هایی که ممکنه امن نباشن

باتشکر
سال نو مبارک
شاد و سربلند باشید

**Comment by ebraminio** [comment]
سلام ظاهراً مشکل برطرف شده، https://gitlab.com/fdroid/fdroiddata/-/issues/2939#note_1326801209 بررسی فرمایید ممنون 😊

**Comment by ebraminio** [comment]
البته انگار مشکل دیگری دارند؟ الآن می‌پرسم، شما هم می‌توانید از همانجا پیگیر باشید

**Comment by ebraminio** [comment]
بالاخره منتشر شد، با تشکر از پیگیری 😊
