### ISSUE TITLE
از اذان فقط الله اکبر را میگوید

### ISSUE THREAD

**Issue by tahapyrs** [persian-calendar/persian-calendar#1059]
سلام من از اف دروید نصب کردم برنامه رو بعد از اذان فقط دو بار میگه الله اکبر .

**Comment by ebraminio** [comment]
درست می‌فرمایید گرامی به دلایلی از جمله پایین نگه حجم برنامه و نداشتن مجوز یک اذان کامل استفاده از اذان کامل به انتخاب اذان سفارشی توسط خود کاربر واگذاری شده است، ممنونم 😊

**Comment by tahapyrs** [comment]
ممنون که وقت گذاشتید ولی هنوز بروزرسانی تو افدروید من نیومده.

**Comment by ebraminio** [comment]
نسخهٔ ۷.۹.۵ چند روز است منتشر شده، دوباره بررسی فرمایید: 😊
https://f-droid.org/packages/com.byagowi.persiancalendar/

**Comment by tahapyrs** [comment]
بروز رسانی کردم، حالا چکار کنم؟

**Comment by ebraminio** [comment]
کار خاصی قرار نبود کنید چیزی عوض نشده 😊

**Comment by RZHSSNZDH** [comment]
> درست می‌فرمایید گرامی به دلایلی از جمله پایین نگه حجم برنامه و نداشتن مجوز یک اذان کامل استفاده از اذان کامل به انتخاب اذان سفارشی توسط خود کاربر واگذاری شده است، ممنونم 😊

یعنی اذان‌های داخل برنامه ناقص هستند؟ دلیل این است؟
