### ISSUE TITLE
اشکال در نمایش روز های تعطیل

### ISSUE THREAD

**Issue by Hamed95ss** [persian-calendar/persian-calendar#1060]
زمانی که تم گوشی من روی حالت شب تنظیم بود و تم روی پیشفرض گوشی بود، برنامه همه روزها را مثل هم نمایش میداد یعنی هیچ تفاوتی بین روز تعطیل و غیر تعطیل نمی شد دید.
ولی وقتی تم های دیگر را انتخاب کردم درست شد.

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید در تم پیش‌فرض در بعضی از رنگ‌هایی که سیستم برای برنامه‌های انتخاب کرده است تفاوت رنگ می‌تواند کم باشد، سعی کردم در https://github.com/persian-calendar/persian-calendar/commit/e4692d4d0d74e01f3e1c474fe0a0f66bc2fe6c61 کمی تفاوتش را پوستهٔ تاریک بیشتر کنم امیدوارم در نسخهٔ بعد بهتر شود، ممنون 😊
