### ISSUE TITLE
رفرش نشدن اتوماتیک تاریخ در نوتیفیکیشن

### ISSUE THREAD

**Issue by Co-mahdi** [persian-calendar/persian-calendar#1064]
سلام 
برای اینکه تاریخ تو نوتیفیکیشن رفرش بشه باید یبار به داخل برنامه بریم تا درست شه مثلا امروز ۲۰ امه اما اگه اخرین بار برنامه رو تو ۱۸ ام باز کرده باشیم تاریخ همچنان ۱۸ رو نشون میده یبار برنامه رو هم پاک کردم گفتم شاید درست شه ولی نشد

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را مشاهده فرمایید، راهنمایی برای حل مشکل از طرف کاربر دارد، ممنونم 😊
