### ISSUE TITLE
گزارشی در مورد تم‌های برنامه

### ISSUE THREAD

**Issue by SaeidArya** [persian-calendar/persian-calendar#1068]
با سلام
ابتدا ممنون از برنامه خوبتون

توی صفحه تقویم وقتی از تم‌های تیره استفاده می‌کنیم تفاوت قابل مشاهده‌ای بین روزهای تعطیل و غیر تعطیل وجود نداره.

با آرزوی بهترین‌ها

**Comment by ebraminio** [comment]
ممنونم بله در #1039 پاسخ دادم 🙏
