### ISSUE TITLE
پیشنهاد ساخت افزونه وردپرس تقویم فارسی

### ISSUE THREAD

**Issue by bihovi584om** [persian-calendar/persian-calendar#1069]
باسلام
از تیم تقویم فارسی و تمام افرادی که در ساخت این برنامه خوب سهیم بودن و نقش داشتند تشکر میکنم؛
جای خالی این برنامه در وردپرس به شدت حس میشه وردپرس از زمان محلی ایران/تهران پشتیبانی میکنه ولی متاسفاته از تقویم شمسی پشتیبانی نمیکنه

از شما تقاضا دارم افزونه ای (پلاگین) برای شمسی سازی تقویم در وردپرس بسازید؛

الان اگر وردپرس فارسی رو دانلود کنید همه بخش ها (به لطف تیم وردپرس فارسی) ترجمه و فارسی هستند اما تقویم شمسی نداره و از تقویم میلادی پشتیبانی میکنه.

(سایت های زیادی از سیستم مدیریت محتوای محبوب وردپرس استفاده میکنن و تقویم هایی هم برای شمسی سازی اون وجود داره اما همگی مشکلات بسیار بزرگی دارن و محصول کم نقصی در این زمینه ندیدم متاسفانه.)

با تشکر و قدر دانی از شما عزیزان.

**Comment by ebraminio** [comment]
سلام گرامی ابتدا ممنون از لطفی که به این برنامه داشته‌اید و ایدهٔ خوبی برای پروژه‌ای جداگانه است و قابل بررسی است، ممنونم
