### ISSUE TITLE
Add weather

### ISSUE THREAD

**Issue by asabouriyan** [persian-calendar/persian-calendar#1070]
Please add weather to app and widget
لطفا نمایش آب و هوای دو هفته آینده را به برنامه و ویجت ها بدون افزایش زیاد حجم و... به این برنامه خوب اضافه کنید
لطفا بدون افزایش استفاده منابع سخت افزاری باشه این مورد ممنون

**Comment by ebraminio** [comment]
سلام گرامی، نیازمند دسترسی به اینترنت است فعلاً سعیمون این هست که برنامه آفلاین کار کنه و جتی دسترسی به اینترنت رو نگیره ولی اگه بعداً دسترسی به اینترنت اضافه شد این مورد واقعاً منطقی و معقول است، ممنونم 😊
