### ISSUE TITLE
اشکال تقویم در تاریخ ۸ اردیبهشت

### ISSUE THREAD

**Issue by madadianpak** [persian-calendar/persian-calendar#1071]
سلام
وقت بخیر
در تقویم شما، مناسبت روز ۸ اردیبهشت را با عنوان «روز جهانی روان‌شناس و مشاور (۲۸ آوریل)» ثبت کرده‌اید و نیاز به اصلاح دارد. چند نکته:
- در تقویم بین‌المللی، روزی با عنوان «روز جهانی روان‌شناس و مشاور» وجود ندارد.
- سازمان ملل (UN) در هر سال یک روزی را (که روز ثابتی هم نیست و در هر سال از اسفند تا اردیبهشت متفاوت بوده است. پارسال ۲۱ آوریل ۲۰۲۲ برگزار شد.) تحت عنوان «روز روان‌شناسی» اختصاص می‌دهد و در سالن همایش جانبی سازمان ملل دو ساعت به این موضوع می‌پردازند و سخنرانی می‌کنند. www.unpsychologyday.com عنوان دقیق آن می‌شود: روز روان‌شناسی در سازمان ملل.
- سازمان نظام روان‌شناسی و مشاوره در ایران از چند سال قبل روز ۹ اردیبهشت را به مناسبت تصویب این سازمان در این روز در مجلس شورای اسلامی به عنوان «روز روان‌شناسی و مشاوره» انتخاب و به شورای انقلاب فرهنگی معرفی کرده است. از آن‌جا که روز ۹ اردیبهشت در تقویم ملی ما به عنوان «روز شوراها» ثبت شده، یک روز را به دو نام تعیین نمی‌کنند و موضوع تا کنون مسکوت باقی مانده است.
- از این رو، درخواست می‌شود عنوانی که در تقویم در ۸ اردیبهشت ثبت کرده‌اید را حذف و در صورت تمایل در تاریخ ۹ اردیبهشت عنوان غیررسمی «روز روان‌شناسی و مشاوره» را ثبت نمایید.
با تشکر
علی مددیان پاک
روان‌شناس دارای پروانه شماره ۳۹۲۲ از سازمان نظام روان‌شناسی و مشاوره کشور

**Comment by ebraminio** [comment]
سلام گرامی، بررسی و تحلیل فوق‌العاده بود، برای نسخهٔ بعد حدف شد، ممنونم، برای افزودن منتظر می‌مانیم که در تقویم رسمی دانشگاه تهران https://calendar.ut.ac.ir/Fa یعنی این فایل https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf برای سال بعد افزوده شود، با تشکر 🙏
