### ISSUE TITLE
افزودن گاه‌شماری شاهنشاهی در بخش برو به تاریخ

### ISSUE THREAD

**Issue by ahmaduxui** [persian-calendar/persian-calendar#1072]
با توجه به اینکه این گاه‌شماری در گذشته تقویم رسمی کشور بوده است و هنوز هم تعدادی از هموطنان از این گاه‌شماری استفاده می‌کنند، لطفا تبدیل گاه‌شماری خورشیدی و میلادی به شاهنشاهی در بخش **برو به تاریخ** را اضافه کنید.

**Comment by ebraminio** [comment]
سلام گرامی از نظر تاریخ مرجع https://calendar.ut.ac.ir/Fa است که می‌توانید با آن‌ها مطرح کنید، ممنون 😊
