### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by Mahantor** [persian-calendar/persian-calendar#1079]
لطفا به نوتیفیکیشن برنامه مناسبت را هم اضافه کنید![Screenshot_2023-04-28-06-47-37-537_com.fox2code.mmm-edit.jpg](https://user-images.githubusercontent.com/91434001/234751325-a297a653-4974-4083-b703-45727cc21aa4.jpg)

**Comment by ebraminio** [comment]
سلام گرامی مناسبت در نوتیفیکیشن نمایش داده می‌شود، شاید این روز خاص دارای مناسبتی نبوده؟

<img alt="image" src="https://user-images.githubusercontent.com/833473/234773430-583e7608-a78e-4f00-99f4-c7e06b053e82.png">

**Comment by ebraminio** [comment]
ممنونم، روزتان احتمالاً جلو باشد، امروز ۲۷ آوریل است، داستان این است که خنثی کردن جلو رفتن ساعت تابستانی در ساعت ۱۱ شب باعث شد که روز دو بار به جلو رود
