### ISSUE TITLE
عدم نمایش تاریخ در نوار نوتیفیکیشن اندروید ۱۰

### ISSUE THREAD

**Issue by aidinzolghadr** [persian-calendar/persian-calendar#1080]
سلام،

نه تو نسخه گوگل پلی و نه بازار، دیگه تاریخ رو تو نوار بالا اندروید نمیبینم، وقتی notification bar رو باز میکنم برنامه اونجا هست و اطلاعاتش هم کامله.

Android 10

نصب چندباره و پاک کردن cache و data هم مشکل رو حل نکرد.

متشکرم

**Comment by ebraminio** [comment]
سلام، اولویت اعلان تقویم پایین هست شاید وجود اعلان‌های متعدد دیگه باعث شده در نوار بالا دیگه اونو نبینید، امکان داره عکسی تهیه کنید؟ ممنونم 😊

**Comment by ebraminio** [comment]
به جیمیلتان فرستادم 😊
