### ISSUE TITLE
روز روان‌شناس و مشاور برابر با 29 آوریل (9 اردیبهشت) در هر سال است تو تقویم نیس

### ISSUE THREAD

**Issue by reza620895** [persian-calendar/persian-calendar#1081]

**Comment by ebraminio** [comment]
سلام گرامی، این روز ظاهراً طبق این مطلب https://t.me/DrPoursharifi/730 جهانی نیست در تقویم ایران است ولی در تقویم ایران هم وجود ندارد، برای افزودن مناسبت‌های https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf لطفاً با مرکز تقویم دانشگاه تهران تماس بگیرید، ممنونم
