### ISSUE TITLE
عدم عملکرد صحیح 

### ISSUE THREAD

**Issue by milad-mantashi** [persian-calendar/persian-calendar#1084]
با عرض سلام و خسته نباشید
نرم افزار Persian Calendar بر روی اندروید ورژن ۱۳ کار نمی کند و در لیست کشویی بالا قرار نمی گیرد. 
با تشکر از زحمات شما 
میلاد منتشی
milad.mantashi@gmail.com

**Comment by ebraminio** [comment]
سلام گرامی، از تنظیمات، برگه اعلان، اعلان برنامه را فعال کنید، در اندروید ۱۳ نیاز دارد خود اینکار را انجام دهید و در صفحهٔ اول برنامه تمایل برای فعال‌سازی ویژگی از کاربر پرسیده می‌شود، ممنونم 😊

**Comment by milad-mantashi** [comment]
سلام ممنون از شما درست شد

**Comment by ebraminio** [comment]
ممنونم 😊
