### ISSUE TITLE
ورودی کیبورد در تبدیل تاریخ

### ISSUE THREAD

**Issue by AryanAhadinia** [persian-calendar/persian-calendar#1112]
در تبدیل تاریخ،‌ برای روز و ماه نمی‌توان ورودی عددی کیبورد وارد کرد. مثلا برای روز اگر روز ۲۴ام مد نظر باشد، باید نوشته شود «چهارشنبه / 24» و نمیتوان مستقیما عدد ۲۴ را وارد کرد. برای ماه نیز باید نام ماه نوشته شود، مثلا «سپتامبر / ۹» و نمیتوان مستقیم ۹ را وارد کرد.

**Comment by ebraminio** [comment]
درست می‌فرمایید و مهم‌تر قبلاً این امکان وجود داشت ولی باعث می‌شد وقتی باز شود به جای «سپتامپر / ۹» از ۹ خالی استفاده شود که به خاطر همین تغییر دادم ولی الآن این مشکل را که می‌فرمایید به وجود آورد تاجایی که می‌فهمم.
