### ISSUE TITLE
نوتیفیکشن

### ISSUE THREAD

**Issue by Vahid4622** [persian-calendar/persian-calendar#1114]
پس از آپدیت کردن در اندروید ۷ دیگه نوتیفیکشن نمایش نمیده، اگر بشود در تنظیمات بصورتی باشه که نوتیفیکشن در صفحه قفل فعال بشه و در بالای صفحه غیر فعال باشد خیلی عالی میشه

**Comment by ebraminio** [comment]
چه اشتباهی الآن برطرف کردم که در انتشاری جدید قرار دهم، قسمت دوم درخواستتان البته به نظر از نظر اندروید ممکن نباشد، مطمئن نیستم، البته شاید بشود آیکون بدون محتوا گذاشت که چندان جالب نباشد

**Comment by Vahid4622** [comment]
چه جالب الان درست شد هنوز آپدیت نکرده!!!

**Comment by ebraminio** [comment]
بله بابت نوع مشکل احتمالش وجود دارد

**Comment by ebraminio** [comment]
الآن هم می‌شود در صفحهٔ ستاره‌شناسی به تاریخ خاصی رفت و موقعیت‌های خورشید و ماه را بررسی کرد و دو کلیک زاویه‌های سایر سیاره‌ها را نسبت به زمین دید ولی شرح آن کمی از اهداف برنامه دور می‌شود با این حال می‌شود به آن فکر کرد، ممنونم 😊

**Comment by Vahid4622** [comment]
من چند سال پیش یه برنامه تقویم نصب کردم و این گزینه طالع بینی چینی رو داشت و برام جالب بود خیلی خوشم آمد و نظرهای مثبتی تو گوگل پلی گرفته بود به همین خاطر به شما پیشنهاد دادم چون برنامتون خیلی عالیه و این گزینه رو کم داره یه چیز دیگه هم که ذهنم رسید جالب میشه که روزهای تعطیل رو در نوتیفیکشن به رنگ قرمز نشون بده 🙏

**Comment by ebraminio** [comment]
درست می‌فرمایید، به هر حال می‌شود به پیشنهادهای مختلف حداقل فکر کرد، ایده‌هایی بوده که بعد از چندسال مطرح شدن توانستم انجام دهم، اعلان در روز تعطیل عنوان روز تعطیل را هنگام باز شدن کشو اعلان با رنگ متفاوتی نشان می‌دهد ولی شاید می‌شد تغییر بیشتری هم داشت

**Comment by Vahid4622** [comment]
منظورم این بود وقتی نوتیفیکشن بسته است و فقط عدد روز را نشان میدهد در روزهای تعطیل رنگ قرمز داشته باشد، قبلاً در یکی از آپدیت ها این گونه بود
