### ISSUE TITLE
Misaligned toggle in settings screen

### ISSUE THREAD

**Issue by MasoudFallahpour** [persian-calendar/persian-calendar#1115]
As seen in the attached image, the last item has a misaligned toggle. Scrolling the page or changing the tab corrects the alignment!

![photo_2023-06-14 21 40 57](https://github.com/persian-calendar/persian-calendar/assets/8100951/974a52d3-29a9-467d-83a6-a370b6055ac2)

**Comment by ebraminio** [comment]
Thanks for the report, weird.

**Comment by ebraminio** [comment]
از آنجایی که برای نسخهٔ بعد بازنویسی شده در آنجا حتماً برطرف می‌شود، ممنونم 😊
