### ISSUE TITLE
مشکل فنی

### ISSUE THREAD

**Issue by amirborzu** [persian-calendar/persian-calendar#1117]
سلام ممنون میشم راهنمایی بفرمایید
مدل گوشی شیائومی پوکو ام ۴ پرو ۴ جی
![IMG_۲۰۲۳۰۶۱۹_۰۱۲۳۱۸](https://github.com/persian-calendar/persian-calendar/assets/137008029/a356ca7b-7479-40d7-a99f-096e9b456be4)

**Comment by ebraminio** [comment]
سلام، دستکاری‌های شیاومی هست از این برنامه کاری برای اصلاح برنمی‌آید یا من اطلاعی ندارم :/ ممنونم 😊
