### ISSUE TITLE
بروز نشدن تاریخ

### ISSUE THREAD

**Issue by aghakhaniamir** [persian-calendar/persian-calendar#1136]
اگر از ویجتهای برنامه روی صفحه گوشی استفاده نشود، تاریخ شمسی نمایش داده شده در بخش notification گوشی، پس‌از تغییر‌ روز، به روز‌ نمیشود و حتما باید یکبار وارد برنامه شویم.

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را مشاهده کنید ممنونم 😊
