### ISSUE TITLE
نبود برخی مناسبات 

### ISSUE THREAD

**Issue by themaahdi** [persian-calendar/persian-calendar#1142]
در ۳۱ مرداد که شهادت است مناسبتی ثبت نشده

در برخی از روز های دیگر نیز بعضی از مناسبات گفته نشده

**Comment by ebraminio** [comment]
سلام گرامی آیا از تنظیمات مناسبت‌های غیرتعطیل را فعال کرده‌اید؟ اگر منظور مناسبت‌های غیر از چیزهایی که در https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf باید با مرکز تقویم دانشگاه تماس بگیرید، ممنونم 😊
