### ISSUE TITLE
Change latin months names in your calander

### ISSUE THREAD

**Issue by Damonsurgery** [persian-calendar/persian-calendar#1144]
Good Time
Please change latin months names 
Today's in international calander ,particularly for Iranian people isn't use aout instead of August 
Please change months names in calander from French to American.
Thanks 😊

**Comment by ebraminio** [comment]
سلام گرامی نام‌های ماه‌های میلادی از مرکز تقویم دانشگاه تهران می‌آید https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201402.pdf برای تغییر با آن‌ها تماس بگیرید، اگر آن‌ها تغییر دهند نه فقط این برنامهٔ کوچک که به بلکه همه برنامه‌ها و تقویم‌های چاپی اصلاح می‌شود، ممنونم 😊
