### ISSUE TITLE
گزینهٔ نام ماه‌های میلادی به تلفظ انگلیسی

### ISSUE THREAD

**Issue by abbaskhalili65** [persian-calendar/persian-calendar#1150]
سلام. روز خوش، لطفا گزینه ای بیفزایید تا بتوانیم ماه های میلادی به زبان انگلیسی داشته باشیم. در تقویم رسمی ایران و تقویم شما به زبان فرانسه هست و متاسفانه برای چک کردن بعضی از ماه ها به مشکل بر می خوریم

**Comment by ebraminio** [comment]
سلام گرامی، با تشکر بابت ایجاد کردن این فایل، من هم علاقه به گذاشتن این گزینه دارم و از نظر فنی چالش خاصی برای افزودن یک گزینه ندارد، امکان دارد هر ۱۲ ماه مورد به تلفظ مورد نظرتان را بفرمایید؟ ممنونم

**Comment by masoudd** [comment]
احتیاجی به فارسی نوشتنشون نیست. من ترجیح میدم اسم ماه‌های میلادی انگلیسی نشون داده بشه. ولی اگه معادل فارسیشون مد نظر هست، [این جدول توی ویکیپدیا](https://fa.wikipedia.org/wiki/%DA%AF%D8%A7%D9%87%E2%80%8C%D8%B4%D9%85%D8%A7%D8%B1%DB%8C_%D9%85%DB%8C%D9%84%D8%A7%D8%AF%DB%8C#%D9%85%D8%A7%D9%87%E2%80%8C%D9%87%D8%A7%DB%8C_%D9%85%DB%8C%D9%84%D8%A7%D8%AF%DB%8C) معادل‌ها رو داره ولی با بعضی‌هاش موافق نیستم من. ستون سوم پیشنهاد من هست.

| English | (از فرانسه) فارسی | فارسی (از انگلیسی تقریبا) |
|--------|--------|--------|
| January | ژانویه | جَنیوئری |
| February | فوریه | فِبریوئری |
| March | مارس | مارچ |
| April | آوریل | آپریل |
| May | مه | مِی |
| June | ژوئن | جون |
| July | ژوئیه | جولای |
| August | اوت | آگوست |
| September | سپتامبر | سپتامبر |
| October | اکتبر | اکتبر |
| November | نوامبر | نوامبر |
| December | دسامبر | دسامبر |

**Comment by ebraminio** [comment]
دو گزینهٔ کاملاً انگلیسی نوشتن و تلفظ تقریبی (نه کامل) از انگلیسی البته گزینه‌های قابل درکی هستند ولی کمی نیازمند زمان بیشتر برای فکر کردن هستند، اگر بتوانم منابعی پیدا کنم که تلفظ تقریبی یکسانی را اینگونه استفاده کرده باشند خیلی خوب می‌شود، ممنونم 🙏

**Comment by ebraminio** [comment]
برای نسخهٔ بعد گزینه‌ای با نام «ماه‌های میلادی با نام انگلیسی» وجود خواهد داشت، ممنونم 😊

**Comment by abbaskhalili65** [comment]
سلام. به نوشتاری انگلیسی هم باشه خوب هست. معادل فارسی هم که فرستادید هم خوب
هست.
سپاس از لطفتون
