### ISSUE TITLE
باگ در برنامه

### ISSUE THREAD

**Issue by Playerbest441** [persian-calendar/persian-calendar#1156]
سلام خسته نباشید برنامه تقویم فارسی شما یک مشکل دارد آن هم اینکه در قسمت اعلان ها که تاریخ را نمایش می دهد تا زمانی که وارد برنامه نشویم اعلان تغییر نمی‌کند ، مثلاً اگر در اعلان شنبه را نمایش دهد اگر فردا هم اعلام ها را نگاه کنی باز هم شنبه است و اگر وارد برنامه شوید اعلان ها یکشنبه میشود

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را مشاهده کنید. ممنونم 😊
