### ISSUE TITLE
مناسبت های ایران باستان

### ISSUE THREAD

**Issue by meelad2** [persian-calendar/persian-calendar#1159]
[مناسبت های ایران باستان](https://github.com/persian-calendar/persian-calendar/blob/03302d2579302f4adc7498a757684f55014cc3e0/PersianCalendar/data/events.json#L36) حتی با وجود فعال کردن در تنظیمات هم نمایش داده نمی‌شوند.
https://raw.githubusercontent.com/ilius/starcal/master/plugins/iran-ancient-data.txt

**Comment by ebraminio** [comment]
سلام گرامی واقعیت اطلاعی ندارم، به نظر که فعال می‌آید؟ از آن نسخه که لینک داده‌اید البته تغییراتی داشته است، احتمالاً منظورتان همان باشد چرا که الآن فعال‌سازی آن را بررسی کردم و مشکلی ندیدم، ممنونم 😊

**Comment by meelad2** [comment]
ممنون

**Comment by ebraminio** [comment]
خواهش می‌کنم اگر مشکلی داشت حتماً بفرمایید 😊
