### ISSUE TITLE
Suggestion: Year view mode

### ISSUE THREAD

**Issue by VadosG** [persian-calendar/persian-calendar#1160]
Hello. I would like to suggest adding a yearly calendar view mode.
There is even a library for this already: https://github.com/m-i-n-a-r/tasticalendar

Many thanks.

**Comment by ebraminio** [comment]
سلام گرامی، پیشنهاد خوبی است که البته کار هم خواهد برد ببینیم چه می‌شود، ممنونم 😊

**Comment by ebraminio** [comment]
The new version 9.0.0, has the feature. Let me know what do you think about it. Thanks 😊

**Comment by VadosG** [comment]
That's awesome. Thank you for that 😊
