### ISSUE TITLE
افزودن فونت فارسی

### ISSUE THREAD

**Issue by only-sadeghi** [persian-calendar/persian-calendar#1161]
درود
لطفا فونت‌های فارسی آقای صابر راستی کردار همچون وزیر و ساحل هم به برنامه اضافه کنید که بشه فونت رو هم تغییر داد.
از نسخه فونتی استفاده کنید که گلیف اعداد فارسی رو هم پشتیبانی کنه.
ممنونم

**Comment by ebraminio** [comment]
سلام گرامی واقعیت استفاده از فونت در ویجت در ساختار فعلی ویجت‌های برنامه دردسر است و اگر نیازمندی‌های اندرویدهای جدید دربارهٔ رنگ‌ها پویا در نظر بگیریم انجام آن را کمی بعید می‌دانم ولی می‌توان به آن فکر کرد، ممنونم 😊

**Comment by only-sadeghi** [comment]
درود، ممنونم.
البته بیشتر منظورم فونت داخل خود برنامه بود.

**Comment by ebraminio** [comment]
با تشکر، ادغام در #527 😊
