### ISSUE TITLE
مناسبت جدید

### ISSUE THREAD

**Issue by mahdicut** [persian-calendar/persian-calendar#1163]
با درود و عرض سپاس خدمت توسعه دهنده های عزیز:
برای روز ٢٣ بهمن مناسبت جدیدی تصویب شده و به تقویم رسمی کشور اضافه میشه از امسال به نام «روز صلح و فوتبال»

**Comment by ebraminio** [comment]
ممنون بابت اطلاع‌رسانی، منتظر تقویم سال جدید هستم که این موضوع در نظر گرفته شود، اگر یادمان رفت حتماً مجدد اطلاع‌رسانی کنید، ممنونم 😊

**Comment by ebraminio** [comment]
در https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201403.pdf وجود نداشت متأسفانه :/
