### ISSUE TITLE
 مشکل باز نکردن برنامه از طریق تایل کوئیک ستینگ در اندروید ۱۴

### ISSUE THREAD

**Issue by Parsiabs** [persian-calendar/persian-calendar#1169]
[Screen Record](https://github.com/persian-calendar/persian-calendar/assets/71925081/076f1b34-2a03-4dde-8dce-ea1a3e921812)

**Comment by ebraminio** [comment]
سلام گرامی، ممنونم، برای نسخهٔ بعد اصلاح شد 😊
