### ISSUE TITLE
the day notification bug

### ISSUE THREAD

**Issue by k5s-co** [persian-calendar/persian-calendar#1173]
The widget and the notification area date, is not updating in 24 hour's period. You have to open the app in order to update the date. It wasn't like this before!
Date is not updated regulary, so we have to open the app to do that. This is an important to show date well in moment without tuching screen. Thank you any way.

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را مشاهده کنید احتمالاً راه‌حل موجود در آنجا برای گوشی‌های مختلف مشکل را برطرف کند، ممنونم 😊
