### ISSUE TITLE
اندازه قسمت برو به تاریخ

### ISSUE THREAD

**Issue by tahashafi21** [persian-calendar/persian-calendar#1174]
![Screenshot_20231027_154241_Persian Calendar](https://github.com/persian-calendar/persian-calendar/assets/90246710/c8a4de9f-bcb4-4a3d-aabb-34929c2d7878)

**Comment by ebraminio** [comment]
سلام گرامی، درست می‌فرمایید، در بعضی گوشی‌ها جای کافی ندارد، باید راه‌حلی برای آن اندیشید، ممنونم 😊

**Comment by ebraminio** [comment]
برای نسخهٔ بعد به کمک تب بازنویسی شده، ممنونم بابت گزارش 😊 

<img width="364" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/d5c5feda-7dea-420c-a445-c30ab6d0ab8c">
