### ISSUE TITLE
اعداد فارسی برای ساعت ویجت

### ISSUE THREAD

**Issue by kraeissi** [persian-calendar/persian-calendar#1175]
برای استفاده در خارج از ایران ، وقتی در ویجت ،  زمان را زمان ایران انتخاب می‌کنیم ، و با اینکه در تنظیمات برنامه ، انتخاب کرده‌ایم که اعداد فارسی نمایش داده شوند ، اما ارقام این ساعت همچنان با عدد پیش فرض خود سیستم ( در اینجا انگلیسی ) نمایش داده می‌شوند که فارسی نبودن ارقام ساعت ، موجب می‌شود آن را با ساعت محلی خارج از کشور اشتباه بگیریم.
لطفاً این اشکال را رفع نموده و کاری کنید در زمان نشان دادن زمان به وقت ایران ، ارقام آن هم اعداد فارسی باشند.
با سپاس

**Comment by ebraminio** [comment]
متأسفانه ارقام ساعت با ارقام دستگاه هماهنگ است و کار خاصی از ما بر نمی‌آید :/
