### ISSUE TITLE
تغییر سایز فونت بدون نیاز به تغییر در تنظیمات اندروید

### ISSUE THREAD

**Issue by ten2120** [persian-calendar/persian-calendar#1178]
وقت بخیر،

ممنون از این برنامه عالی شما. بعد از نصب حدودا ۱۵ برنامه (تقویم فارسی) به این نتیجه رسیدم همشون آشغالی بیش نبودن! به غیر از این برنامه. کم حجم، سبک، فقط شامل موارد مورد نیاز نه بیشتر!

تنها مشکلی که با این برنامه دارم، نوع قلم (فونت) و سایز قلم هست. تقاضایی که دارم، در آپدیت (های) بعدی، فونت رو به IRYekan (بابت خوانایی) تغییر بدید و گزینه‌ای داخل خود برنامه برای تنظیم اندازه (سایز) فونت ویجت در نظر بگیرید. روی گوشی با اسکرین چگال (High PPI Screen)، فونت ویجت بسیار ریز و ناخواناست. مگر از تنظیمات فونت اندروید (Settings>Display>Text Size) اندازه‌ی فونت کل گوشی رو یزرگ کنیم، که منطقی به نظر نمیرسه.

تا اونجا که به خاطر دارم، سری فونت IR تحت مجوز رایگان ارائه شدن (۳۲ فونت یونیکد شده توسط شورای عالی انفورماتیک ایران) و مشکل لیسانس ندارن.

**Comment by ebraminio** [comment]
سلام گرامی، در ابتدا ممنون بابت لطفی که به این برنامه دارید 😊 واقعیت استفاده از قلم در ویجت در ساختار فعلی ویجت‌های برنامه دردسر است و اگر نیازمندی‌های اندرویدهای جدید دربارهٔ رنگ‌ها پویا در نظر بگیریم انجام آن را کمی بعید می‌دانم ولی می‌توان به آن فکر کرد، و من واقعیت کمی دربارهٔ مجوز قلم مشکوکم، البته استفاده از آن نشد نیست ولی همچنان حس خوبی که استفاده از اجزایی که آزاد هستند را ندارد، و واقعیت تغییر قلم پیش‌فرض برنامه را به توجه به زبان‌های دیگری که در این برنامه استفاده می‌شود و نیازمندی بعضی از کاربران به تنظیم قلم خاص خود در برنامه‌ها کمی بعید می‌دانم و احتمالاً تبدیل به گزینه‌ای می‌شود که بعید می‌دانم بشود به راحتی در هر جایی که اثری از برنامه وجود دارد، مثلاً اعلان و ویجت، به راحتی و بدون دردسر اعمال کرد و که اگر چنین کمی برای کاربر سورپرایز اعمال کرد، ممنونم 😊

**Comment by ten2120** [comment]
ممنون بابت وقت و توضیحات. فقط من باب اطلاع عرض میکنم (و اگر وقت کافی داشتید) میتونین یک نگاهی به فونت «وزیر متن» هم بندازین. تحت لیسانس OFL (مالکیت عمومی)، دارای ۹ وزن و شامل یک وزن Variable. 
https://github.com/rastikerdar/vazirmatn

امیدوارم گزینه‌ی تغییر سایز (همین قلم/فونت فعلی) در برنامه رو اضافه کنید. روی اسکرین بزرگ، بسیار ریز و ناخواناست.

**Comment by ebraminio** [comment]
بله در #527 بررسی می‌کردیم، در آن ایشو ادغام می‌کنم، ممنونم 😊

**Comment by ten2120** [comment]
ممنون 🙏🏻
