### ISSUE TITLE
تغییر فونت برنامه

### ISSUE THREAD

**Issue by MahdiFarzami** [persian-calendar/persian-calendar#1186]
امکان این هست که فونت برنامه عوض بشه و یا قابلیت انتخاب فونت اضافه بشه ؟

**Comment by ebraminio** [comment]
سلام گرامی نشد نیست ولی ملاحظاتی دارد مثلاً در https://github.com/persian-calendar/persian-calendar/issues/527 افراد مختلف فونت‌های مختلف را می‌پسندند پس باید فونت‌های مختلف را گذاشت که باعث بالا رفتن حجم می‌شود، برنامه از زبان‌های مختلف حمایت می‌کند و باید فونتی که مثلاً حروف اردو و پشتو را هم داشته باشد استفاده شود و پیاده‌سازی‌اش حداقل به خاطر ساختار فعلی ویجت و نیازهایی که اندروید ۱۲ در رنگ پویا دارد در ویجت و اعلان توان را ندارد که دارای ایراد خواهد بود که به این دلایل چندان تغییر مطلوبی نیست، ادغام در https://github.com/persian-calendar/persian-calendar/issues/527 ممنونم 😊
