### ISSUE TITLE
قابلیت تغییر مبدا سال شماری

### ISSUE THREAD

**Issue by arya-prof** [persian-calendar/persian-calendar#1187]
قابلیت تغییر مبدا سال شماری را اضافه کنید. مبدا های تقویم های شمسی مرسومی که استفاده می شوند مانند تقویم های شاهنشاهی، یزدگردی و جلالی.

**Comment by ebraminio** [comment]
سلام گرامی ممنون از پیشنهاد واقعیت کمی می‌ترسم گرفتار حواشی شویم، ممنونم 😊
