### ISSUE TITLE
درخواست قابلیت جدید: سال در یک نگاه

### ISSUE THREAD

**Issue by rzasharifi** [persian-calendar/persian-calendar#1190]
درود. لطفاً قابلیت دیدن سال در یک نگاه هم اضافه کنید. اینطوری راحت‌تر میشه دید کجای سال هستیم، توی کدوم ماه ها چندتا تعطیلی داریم، چند هفته تا یک تاریخ خاص مونده، توی کدوم تاریخ یک رویداد رو بذاریم و برنامه بچینیم بهتره و دیگر مزایا.
در این قابلیت علاوه بر روزهای تعطیل اگر روزهایی که رویدادهای شخصی با علامتی خاص مشخص بشه که با تاچ طولانی مثلا بشه فهمید اون رویداد چیه و چه ساعتی هم که عالی خواهد بود.

**Comment by ebraminio** [comment]
پیشنهاد منطقی‌است، کمی اینکه چگونه جزئیات اینکه در اندازه‌های مختلف صفحه و صفحهٔ عمودی و افقی چگونه شود و اینکه چگونه باید به این قسمت برنامه رفت یا خارج شد کمی انجامش را سخت می‌کند که البته قطعاً نشد نیست.

**Comment by rzasharifi** [comment]
`چگونه باید به این قسمت برنامه رفت یا خارج شد`
برای این قسمت، من پیشنهاد می‌کنم که از قابلیت دو انگشتی استفاده بشه. به این صورت که اگر دو انگشت رو به هم نزدیک کنیم نمای سالانه پدیدار بشه و اگر دو انگشت رو از هم دور کنیم وارد نمای ماهانه بشیم (مثل قابلیت موجود در نقشه‌ها و عکس‌ها)
هر چند که قطعاً جاهای دیگه‌ای مثل سه نقطه میشه تعبیه‌اش کرد
![Screenshot_2023-11-15-18-38-21-940_com byagowi persiancalendar-edit](https://github.com/persian-calendar/persian-calendar/assets/64254187/72aab59c-b6bc-4431-862e-038f6e126fdc)

**Comment by ebraminio** [comment]
نمونهٔ اولیهٔ این قابلیت 😊

<img width="373" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/e28687d3-271d-4bae-8d94-b1641af43e4d">

**Comment by ebraminio** [comment]
https://github.com/persian-calendar/persian-calendar/commit/68d1f1fe18e44d59b8f0c9bd6decb559d7dd9ac7

با تشکر از پیشنهادتان برای نسخهٔ بعد انجام شد 😊

**Comment by rzasharifi** [comment]
درود و سپاس برای ترتیب اثر. پیشنهاد میکنم اگر امکانش هست برای شکیل‌تر شدنش هر ماه رو بذارید توی یک حباب‌طوری! مثل این
![Uploading Screenshot_2023-12-30-14-12-45-379_com.miui.home.jpg…]()

**Comment by ebraminio** [comment]
<img width="370" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/61377b5f-ee85-440d-b811-aa802b6ff73b">


فکر خوبی است اعمال شد 😊
