### ISSUE TITLE
How to change Iranian year(1402) to Kurdish year(2723) in project

### ISSUE THREAD

**Issue by Hiwaselah** [persian-calendar/persian-calendar#1209]
Hello my brothers, thank you for your beautiful work.
How to change Iranian year(1402) to Kurdish year(2723) in project?

I'm from Kurdistan

i need change  Shamsi year to Kurdish year
1402 to 2723

this is my app:
https://play.google.com/store/apps/details?id=com.hiwaselah.kurdishcalendar

**Comment by kyanasadii** [comment]
سلام کاک هیوا ابه دیتابیسکی تواو کوردی بو بنوسی

**Comment by Hiwaselah** [comment]
چۆ دەبێت زۆر پێویستمە

**Comment by Hiwaselah** [comment]
چۆن دەبێت زۆر پێویستمە؟
How can I need it so much?

**Comment by Hiwaselah** [comment]
اخي اني كورد لازم للكوردستان تغير تقويم شمسي إلى كردي
أخي ، أنا كردي ، أولا جزاك الله خيرا على هذا البرنامج المفيد ، ولكن كما تعلمون ، فإن السنة الكردية تختلف عن السنة الإيرانية.
لكي يتخلص شعب كردستان مني ، كنت بحاجة إلى تغيير السنة الإيرانية من ١٤٠٢ إلى ٢٧٢٣ ... أتمنى لك يومًا لطيفًا.

براکەم من کوردم دەست خۆشیتان لێ دەکەم بۆ ئەو بەرنامە بێ وێنە و بە سوودە بەڵام وەکو دەزانن ساڵی کوردی جیاوازە لە ساڵی ئێرانی جا بۆ ئەوەی خەڵکی کوردستان سوردی لێ وەربگرن پێویستم بەوە بوو ساڵە ئێرانییەکە لە ١٤٠٢ بگۆڕم بۆ ٢٧٢٣ ... دەستتان خۆش بێت...

My brother, I am a Kurd, I would like to congratulate you on this unparalleled and useful program, but as you know, the Kurdish year is different from the Iranian one.
In order for the people of Kurdistan to get rid of me, I needed to change the Iranian year from 1402 to 2723 ... Have a nice day ...

**Comment by Hiwaselah** [comment]
پێشتر لە ڤێرشنەکانی پێشوو برایەک لێرە بەناوی کاک @ebraminio یارمەتی دام چوار ساڵ پێش ئێستا
ئەمەش لینکی وەڵامەکەیەتی بەڵام ئێستا پڕۆژەکە زۆر گۆڕاوە.

Earlier in previous versions a brother here named Mr. @ebraminio  helped me four years ago
 Here is a link to the answer but now the project has changed a lot

https://github.com/persian-calendar/persian-calendar/issues/555

**Comment by Hiwaselah** [comment]
Please help me my brothers...

**Comment by ebraminio** [comment]
Hi. Accurately showing them including appropriate leap years for the coordinations is a hard task currently and for now is an out of scope this project and last time I helped I wasn't aware of complication it has and you didn't disclose your changes so I can help more with it and I think it's a little late now. Thanks 😊
