### ISSUE TITLE
شب یلدا 

### ISSUE THREAD

**Issue by Eymur73** [persian-calendar/persian-calendar#1217]
شب یلدا و بعضی از مناسبت های پرطرفدار ایرانی نوشته نشده در مناسب های تقویم شما امیدوارم در آپدیت جدید این مشکل رو حل کنید

**Comment by ebraminio** [comment]
شب یلدا که به نظر وجود دارد،

<img width="373" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/5024b80d-c8da-40d9-a33f-1f23d411ebb5">

**Comment by Mehrdad-Farshi** [comment]
سلام @Eymur73 مشکلی که مطرح کردید رو من هم داخل برنامه متوجه شدم . برای دیدن مناسبت های ایرانی  باید داخل برنامه به تب `تنظیمات` برید - در بخش `رابط و تقویم` - `تقویم` - `مناسبت ها` رو کلیک کنید  و تیک 

- [ ] `سایر مناسبت های ایرانی`

 رو فعال کنید 
 
 یلدات هم مبارک   :melon:  :smiley:

**Comment by ebraminio** [comment]
https://github.com/persian-calendar/persian-calendar/blob/main/FAQ.fa.md

قسمت دوم، مناسبت‌ها
