### ISSUE TITLE
مغایرت مناسبت ها

### ISSUE THREAD

**Issue by aminlakzaee** [persian-calendar/persian-calendar#1228]
با سلام و خسته نباشید 
امروز مورخه 
۱۶ دی ۱۴۰۲ 
مناسب با روز غرق شدن کشتی سانچی میباشد.
در مناسب ها اعمال شود 
با تشکر

**Comment by ebraminio** [comment]
سلام گرامی در تقویم https://calendar.ut.ac.ir/Fa/News/Data/Doc/Calendar%201403.pdf ذکر نشده، لطفاً با مرکز تقویم دانشگاه تهران تماس بگیرید، ممنونم 😊
