### ISSUE TITLE
پرسش از وجود نرم افزار ویندوز تقویم پارسی

### ISSUE THREAD

**Issue by Shahabinia** [persian-calendar/persian-calendar#1230]
باسلام و درود
ابتدا از اینکه این تقویم پارسی بسیار خوب را ساخته‌اید بسیار سپاسگزارم
آیا این نرم‌افزار برای ویندوز هم تولید شده است؟

ممنون

**Comment by ebraminio** [comment]
سلام گرامی، در حال حاضر خیر ولی احتمال اینکه این پروژه در آینده به کمک امکانات KMM به ویندوز هم برسد هم وجود دارد، ممنونم 😊
