### ISSUE TITLE
از بین رفتن دسترس‌پذیری با Talkback

### ISSUE THREAD

**Issue by mohammadrezarashad** [persian-calendar/persian-calendar#1245]
با درود. در نسخه‌ی ۹.۰.۰، هنگامی که تقویم را باز می‌کنم، به جای اینکه مثل سابق روزهای ماه را بشنوم، عبارت «بدون برچسب» را به جای هر روز می‌شنوم. برنامه‌ی تقویم فارسی پیش از این برای کاربران نابینای اندروید با صفحه‌خوان‌های موجود بویژه Talkback بسیار دسترس‌پذیر بود. لطفا نسبت به بازگرداندن دسترس‌پذیری این برنامه اقدام بفرمایید. سپاسگزارم.

**Comment by ebraminio** [comment]
سلام گرامی، با اینکه من حواسم به این موضوع بوده متأسفانه در بازنویسی برنامه اشتباهی مقدار برچسب را جای درست نگذاشته بودم و فکر می‌کردم همین که بر خود کلیک برچسب بگذارم در TalkBack خوانا خواهد بود ولی نیاز بود کلیک و محتوا را جداگانه برچسب بگذارم که همین الآن برای نسخهٔ بعد این موضوع رو در جای‌های مختلف برنامه اعمال کردم، با تشکر از پیام فوق‌العاده و به موقع شما.

**Comment by mohammadrezarashad** [comment]
سلام. سپاس فراوان از دقت و پیگیریتون. براتون آرزوی تندرستی و پیروزی
دارم. باز هم از طرف خودم و همنوعانم از توسعه و بروزرسانی این برنامه‌ی
بسیار کاربردی و عالی ازتون سپاسگزارم.

-- 
     Best wishes,
     Mohammadreza Rashad
