### ISSUE TITLE
اپدیت تقویم در سیستم عامل جدید HyperOS

### ISSUE THREAD

**Issue by irmacfa** [persian-calendar/persian-calendar#1247]
سلام وقت بخیر
شیائومی سیستم عامل HyperOS رو برای گوشی های جدید انتشار داده مثل 12T Pro ، پس از نصب  در ناتیف بار پاک میشه ممنون میشم اپدیت کنین سپاسگزارم

**Comment by ebraminio** [comment]
سلام گرامی، شرمنده بابت تأخیر در پاسخ، نمی‌دانم در HyperOS چه کرده‌اند و متأسفانه دسترسی به این دستگاه هم ندارم :/

**Comment by ali-zali-dev** [comment]
سلام. وقت بخیر
فکر کنم این مورد به خاطر تغییرات اندروید ۱۴ باشه که گوگل ایجاد کرده و تو این [https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications](url) توضیح داده شده

در واقع همه ی نوتیفیکیشن ها رو میشه پاک کرد مگر اینکه دکمه Clear all بزنید که در این صورت نوتیف های non-dismissable مثل نوتیف تقویم پاک نمیشند.
@ebraminio فکر کنم این ایشو بهتره بسته بشه
