### ISSUE TITLE
Dear sir/madam

### ISSUE THREAD

**Issue by abed2525** [persian-calendar/persian-calendar#1261]
Thank you very much for your very useful app,
I think before version of " persian calendar " notification  could be up-to-date    but recrecent version of the app has not the ability.
Please modify thus nice app for all persian language users.
Thank you

**Comment by ebraminio** [comment]
سلام گرامی اندرویدتان چه نسخه‌ای است؟

**Comment by ebraminio** [comment]
احتمالاً در نسخه‌های اخیر بهتر شده باشد، ممنونم 😊
