### ISSUE TITLE
مشکل چپ‌چین‌شدن نوتیفیکیشن

### ISSUE THREAD

**Issue by alirezacyrus** [persian-calendar/persian-calendar#1273]
سلام
متون فارسی در نوتیفیکیشن تقویم علی‌الاصول باید به حاشیه راست چسبیده و راست‌چین باشند، اما مثل متون انگلیسی، به سمت چپ چسبیده‌اند.
مشابه این مشکل را کاربر دیگری هم مطرح کرده بود.
Android 13
Samsung Galaxy A52

**Comment by ebraminio** [comment]
در Dark Mode اینگونه می‌شود؟ مربوط به این [خط](https://github.com/persian-calendar/persian-calendar/blob/364882d/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/utils/UpdateUtils.kt#L901-L905) از برنامه است که یا نمی‌توان هم اعلان سفارشی راست‌به‌چپ در سامسونگ داشت هم اعلان تاریک مگر اینکه به تازگی اصلاج شده باشد

**Comment by alirezacyrus** [comment]
بله، تنها در حالت دارک این مشکل وجود دارد.

**Comment by ebraminio** [comment]
در اندروید ۱۴ سامسونگ مشکل برطرف شده و تقویم هم در ان اندروید اعلان را راست‌به‌چپ در تاریک نشان می‌دهد، با تشکر 😊
