### ISSUE TITLE
چهارشنبه سوری

### ISSUE THREAD

**Issue by yousefebrahimi0** [persian-calendar/persian-calendar#1283]
چرا چهارشنبه سوری در سال‌های اخیر از این اپ به طور کامل حذف شده؟

**Comment by ebraminio** [comment]
سلام گرامی، آیا مناسبت‌های غیرتعطیل را از تنظیمات فعال کرده‌اید؟ این مناسبت امسال حتی به تقویم مرکز تقویم دانشگاه تهران با نام تکریم همسایگان اضافه شده است که در این برنامه هم قابل مشاهده است. ممنونم
