### ISSUE TITLE
زمان اعلان اذان و ویجت ساعت در گوشی هایی که ساعتشان دستی نیست و +4:30 هستند در نیمه اول سال اشتباه است

### ISSUE THREAD

**Issue by 0xRustlang** [persian-calendar/persian-calendar#1295]
سلام

ساعت اعلان اذان یا پخش اذان درگوشی هایی که ساعت آنها یک ساعت به جلو رفته است (و تایم زون آنها +4:30 است) و کاربر در آنها به دلایل عدم ایجاد تداخل در بعضی نرم افزار ها نمیتوانند ساعت را روی دستی قرار دهند و دستی به عقب بکشند اشتباه پخش میشود

یعنی بر فرض ساعت گوشی (با تایم زون +4:30) روی 18:20 دقیقه است (درحالی که ساعت رسمی کشور (با تایم زون استاندارد +3:30) روی 17:20 دقیقه است.

همچنین اوقات شرعی امروز نیز 18:20 بوده است.

در این حالت گوشی من یکساعت زودتر اذان را اعلام میکند

چرا که اوقات شرعی در تقویم طبق این قسمتی که قبلا فرمودید الان در گوشی های قدیمی درست نوشته میشود (https://github.com/persian-calendar/persian-calendar/issues/1049#issuecomment-1483708786)

ولی تقویم برای اعلان اذان، به زمان گوشی وابسته است و درنتیجه اشتباه یکساعت زودتر اعلان اذان میکند

همچنین ویجت تقویم هم ساعت را طبق ساعت دستگاه نشان میدهد که اشتباه است

برایتان امکان پذیر است که مثل همان اصلاحیه ای که برای نمایش زمان اوقات شرعی درگوشی های قدیمی دادید (https://github.com/persian-calendar/persian-calendar/issues/1049#issuecomment-1483708786)

برای ویجت ساعت و زمان اعلان اذان هم آن دو قسمت از کد های برنامه را نیز برای گوشی های قدیمی روی تایم زون +3:30 فیکس کنید؟

باتشکر فراوان

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید، شیوه‌های مختلف و متنوعی کاربران برای حل این مشکل در دستگاه خود دارند که هماهنگی با آن‌ها کمی دارای چالش و تناقض است به همین خاطر در این پروژهٔ چندان به فکر آن نیستم خصوصاً که سال پیش این موضوع را کاربران مدیریت کرده‌اند، ممنونم 😊

**Comment by ebraminio** [comment]
> امکان دارد درگزینه «فاصله بین اذان واقعی و اعلان» قابلیتی بگذارید که عدد منفی برای دقیقه قرار دهیم؟

الآن هم می‌شود منفی قرار داد تاجایی که می‌دانک
