### ISSUE TITLE
لایسنس فایل‌های json

### ISSUE THREAD

**Issue by be4zad** [persian-calendar/persian-calendar#1297]
درود.

تا اونجایی که من اطلاع دارم GPL برای سورس کد برنامه استفاده می‌شه. این وسط تکلیف این فایل‌های json چی می‌شه و تحت چه لایسنسی قرار می‌گیرن؟ یا اصلاً لایسنس ندارن؟

این فایل‌ها کاربردی هستند و قصد دارم در یک پروژه آزاد (با لایسنس MPL-2.0) از اون‌ها استفاده کنم.

**Comment by ebraminio** [comment]
سلام ظاهراً که برای غیر نرم‌افزار هم قابل استفاده است https://en.wikipedia.org/wiki/GNU_General_Public_License#Text_and_other_media به نظرم با حفظ لایسنس می‌توانید استفاده کنید، viral بودن آن احتمالاً تأثیری نخواهد داشت و آنقدر جای نگرانی هرچند من در موقعیتی نیستم که آن را مجاز کنم یا غیر مجاز ولی تاجایی که می‌دانم مشکلی نخواهد داشت، ممنونم 😊

**Comment by be4zad** [comment]
من روی این موارد وسواس دارم و اگر GPL محسوب می‌شن اخلاقی نیست که استفاده کنم و هرگز هم نمی‌کنم. به حفظ لایسنس اشاره کردید که این مورد برای کتابخانه‌ها مقدور نیست چون هرگز نمی‌تونن GPL باشن.

اگر صلاح دونستید می‌تونید پروژه رو Dual license کنید (GPL-3.0 + MPL-2.0) و فایل‌های json رو تحت MPL قرار بدید. اگر خواستید اطلاع بدید تا دقیق راهنماییتون کنم.

خیلی ممنونم که پاسخ دادید.
