### ISSUE TITLE
درخواست برای اضافه کردن یک ویژگی در ساعت تقویم 

### ISSUE THREAD

**Issue by Rahiemie** [persian-calendar/persian-calendar#1299]
سلام
با توجه به اینکه ساعت خیلی از گوشی‌های نسبتاً قدیمی با تغییر ساعتی که در ایران انجام شده ۶ ماه اول سال یک ساعت جلوتر نشون میده، اگر بشه ساعت ویجت ها رو تنظیم کرد که time zone های مختلف رو بتونیم تنظیم کنیم حداقل برای دیدن ساعت از روی گوشی مشکلمون حل میشه، اگه بشه روی لاک اسکرین هم ویجت ساعت رو اضافه کرد که عالیه.
ممنون

**Comment by ebraminio** [comment]
سلام گرامی کمی دردسر دارد خصوصاً که قابلیت‌های مختلفی از جمله یادآور تقویم و غیره در برنامه وجود دارد و کاربران مختلف راه‌حل‌های مختلفی برای آن دارند به خاطر همین در حال حاضر پیشنهادم استفاده از برنامهٔ دیگری است، این برنامه https://github.com/ebraminio/fixed-clock/actions/runs/8419348137/artifacts/1355364914 که سورسش در https://github.com/ebraminio/fixed-clock قرار دارد ساعت روی لاک‌اسکرین هم هست و شاید مناسبت نیازتان هم باشد، اگر آنرا بررسی کردید حتماً مرا از نتیجه مطلع کنید، ممنونم 😊
