### ISSUE TITLE
مشکل در اندروید 14

### ISSUE THREAD

**Issue by bihovi584om** [persian-calendar/persian-calendar#1300]
سلام در اندروید 14 وقتی در نوار اعلانات ویجت تقویم فارسی رو به یک طرف بکشی و حذف کنی تا دوباره برنامه رو باز نکنی اعلان تقویم نمیاد اما در اندروید 13 اعلان تقویم فارسی حذف نمیشد حتی با کشیدن به طرفین،
میشه کاری کنید در اندروید 14 که حتی با کشیدن طرفین هم حذف نشه اعلان تقویم فارسی؟

**Comment by ebraminio** [comment]
سلام گرامی تغییر از طرف گوگل است و از طرف این برنامه کاری بر نمی‌آید :/
