### ISSUE TITLE
مشکل فونت

### ISSUE THREAD

**Issue by Davoud86** [persian-calendar/persian-calendar#1301]
سلام دوستان
با فونت میخک دستگاه من مشکل داره و در نمایش داده به طور کامل نشون نمی‌ده
![Uploading Screenshot_2024-03-28-01-34-51-436_com.miui.home.jpg…]()
اگر میشه بگین چه کنم

**Comment by ebraminio** [comment]
سلام گرامی تصویر نرسیده، اگر ممکن است مجدد آپلود کنید ممنونم
