### ISSUE TITLE
بهبود برنامه

### ISSUE THREAD

**Issue by 50h31l** [persian-calendar/persian-calendar#1314]
توی آخرین اپدیت انیمیشن ها عالی شده فقط یه مشکل جزئی هست اونم اینه که مثل قبل برنامه روان نیس مثلا موقعی که قسمت dropdown اوقات شرعی رو میزنیم یکم تیکه تیکه باز میشه. مثل این هست که اف پی اس برنامه رو روی ۳۰ گذاشته باشیم.

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید، شخصاً حس می‌کنم از زمان تبدیل برنامه به compose اینگونه شده ولی شاید هم ایرادی از کدهای ما باشد، فعلاً کاری از ما بر نمی‌آید ولی ببینیم چه می‌شود، ممنونم 😊
