### ISSUE TITLE
Add option to save events in the app

### ISSUE THREAD

**Issue by Gamer750** [persian-calendar/persian-calendar#1315]

**Comment by ebraminio** [comment]
سلام گرامی، یعنی به غیر از امکان فعلی ذخیره در تقویم دستگاه، درون برنامه و سینک نشده؟ نیازمند دسترسی‌های بیشتر و پیچیدگی بیشتر خواهد بود که احتمالاً در این پروژه سخت یا ناممکن باشد، ممنونم 😊
