### ISSUE TITLE
نبودن مناسبت یازدهم اردیبهشت روزکارگر

### ISSUE THREAD

**Issue by theuser17** [persian-calendar/persian-calendar#1316]
در آپدیت جدید 11 اردیبهشت روز کارگر نیست! فقط روز جهانی کارگر وجود داره

نگارش 9.1.5

**Comment by ebraminio** [comment]
<img width="348" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/3e6380a0-f354-4f45-a78e-2a1aa70628a0">

<img width="971" alt="image" src="https://github.com/persian-calendar/persian-calendar/assets/833473/8684f2d1-5622-4db9-ab12-2cd5c8fbd8da">

ظاهراً که باید ۱۲ اردیبهشت باشد طبق مرکز تقویم و در حال حاضر وجود دارد؟ ممنونم

**Comment by theuser17** [comment]
والا میگن 12م روز جهانی هست، ولی روز کارگر همون 11 هست 🤔

**Comment by theuser17** [comment]
والا میگن 12م روز جهانی هست، ولی روز کارگر در کشور ایران همون 11م هست 🤔

منبع: https://mehrnews.com/x34Nkx

**Comment by ebraminio** [comment]
پس شاید بشود با مرکز تقویم تماس گرفت چون سعی در اینجا هماهنگی با تقویم مرکز تقویم است
