### ISSUE TITLE
 ایجاد رویداد داخل تقویم فارسی

### ISSUE THREAD

**Issue by Parsiabs** [persian-calendar/persian-calendar#1331]
لطفاً قابلیت ایجاد رویداد های تکرار شونده با استفاده از تقویم خود برنامه اضافه گردد.

**Comment by ebraminio** [comment]
سلام گرامی، صرفاً پیاده‌سازی آن سخت نیست ولی کاربر توقع پشتیبانی‌گیری خواهد داشت چنان که همین الآن برای مناسبت‌هایی که در تقویم دستگاه ذخیره می‌شوند گاهی ایمیلی دریافت می‌کنم که دربارهٔ نحوهٔ پشتیبانی‌گیری سوال یا شکایت می‌کنند در حالی که آن کاملاً به‌عهدهٔ تقویم دستگاه است و برای پشتیبانی‌گیری نیاز به import و export و دسترسی خواهد داشت یا باید از کتابخونه گوگل پلی را استفاده کرد یا باید دسترسی به اینترنت داشت که مطلوب این برنامه نیست، ممنونم 😊
