### ISSUE TITLE
تکرار رویدادها

### ISSUE THREAD

**Issue by alidve** [persian-calendar/persian-calendar#1345]
data api
برای گوگل کلندر سه یار میاده ![Screenshot_2024-06-17-15-49-00-098_com.byagowi.persiancalendar.jpg](https://github.com/persian-calendar/persian-calendar/assets/59482995/4636f5df-3df1-422d-942d-c69ade3b8614)

**Comment by ebraminio** [comment]
سلام گرامی مشکل را قبلاً دیده بودم ولی تاجایی که می‌دانم ناشی از آن بوده که چنین رویدادی از چند منبع به تقویم دستگاه اضافه شده و با مشورت با دیگران به این نتیجه رسیدم که بهتر است کاری در رابطه با آن انجام ندهیم، به همین خاطر اگر امکان دارد تقویم دستگاه را بررسی کنید، ممنونم
