### ISSUE TITLE
از کار افتادن

### ISSUE THREAD

**Issue by aarsham77** [persian-calendar/persian-calendar#1346]
درود وقت بخیر
برنامه عالیه ولی تو گوشی جدیدم نه بالای گوشی میاد و نه بخش نوتیف 
گاهی  بخش نوتیف رو بکشم پایین هست ولی همیشه نه 
گوشیم شیامیه

**Comment by ebraminio** [comment]
سلام گرامی شاید این راهنما https://dontkillmyapp.com بتواند مفید باشد از طرف برنامه و کد واقعاً اصلاحی به ذهنم نمی‌رسد که با گوگل پلی و اندرویدهای جدید هماهنگ باشد، با عرض شرمندگی، ممنونم
