### ISSUE TITLE
نوتیفیکشن

### ISSUE THREAD

**Issue by MAHBOZ** [persian-calendar/persian-calendar#1362]
[persian-calendar.html.pdf](https://github.com/user-attachments/files/16050765/persian-calendar.html.pdf)
سلام
در بالای صفحه نوتیفیکشن تاریخ که به صورت تک عدد بود نمایش داده نمیشه
![Screenshot_20240701_125249](https://github.com/persian-calendar/persian-calendar/assets/114846902/2fd092f6-08c7-46be-952f-cafe57c5e6e7)

**Comment by ebraminio** [comment]
سلام گرامی آیا اندرویدتان ۱۳ به بالاس؟ چون آنجا یک گزینه برای فعال‌سازی اعلان وجود دارد، اگر نبود به نظرم یک‌بار برنامه را حذف و نصب کنید، ممنونم 😊

**Comment by ebraminio** [comment]
اولین بار است که برای اندروید ۱۰ چنین چیزی می‌شنوم یا به خاطر ندارم چنین چیزی را، در حال حاضر شرمنده‌ام که چیزی به ذهنم نمی‌رسد 😞

**Comment by MAHBOZ** [comment]
ممنون از ادب و پاسخگویی خوبتون، دلیلش رو پیدا کردم، gentle notification باید خاموش باشه 🌹

**Comment by ebraminio** [comment]
فوق‌العاده، ممنونم بابت اطلاع‌رسانی، من اسم این قابلیت را نشنیده بودم سعی می‌کنم، سعی می‌کنم اگر دفعهٔ بعد شخصی در این رابطه پرسید این یکی از گزینه‌هایی باشد که در رابطه با آن بپرسم، ممنونم 🙏
