### ISSUE TITLE
مشکل قفل بودن اعلان در اندروید ۱۴

### ISSUE THREAD

**Issue by shahryarse** [persian-calendar/persian-calendar#1376]
سلام. من از اندروید ۱۴ ، تلفن galaxy a55 استفاده میکنم. اعلان در بالای صفحه قفل نمیشود و با حذف اعلان ها قابل پاک شدن است.

**Comment by ebraminio** [comment]
سلام گرامی از قابلیت‌های اندروید جدید است و از طرف ما کاری برنمی‌آید :/
