### ISSUE TITLE
مشکل تاریخ

### ISSUE THREAD

**Issue by r1ma952** [persian-calendar/persian-calendar#1398]
سلام. تاریخ تولد من ۲۷ مهر یعتی ۱۹ اکتبر هست. در صورتیکه در تقویم میزنه ۱۸ اکتبر. ساعت و تاریخ گوشی ام هم درست است. چیکار کنم مرسی؟

**Comment by ebraminio** [comment]
سلام گرامی، این مورد ناشی از اختلاف سال میلادی و شمسی است و نمایش آن در تاریخ درست به عهدهٔ تقویم گوگل است که این برنامه صرفاً به‌صورت پوستهٔ آن عمل می‌کند، ممنونم

**Comment by r1ma952** [comment]
چیکار کنم که اشتباه نکنم موقع استفاده از برنامه پرشین کالندار؟

**Comment by r1ma952** [comment]
من چون استفاده روزانه دارم از پرشین کالنذر و از برنام Todoist هم برای وارد کردن تاریخ ها استفاده میکنم. نمیخواهم اشتباه کنم. ممنونم اگر راهنمایی فرمایید ممنونم

**Comment by r1ma952** [comment]
خیلی ممنون میشم راهنمایی کنید

**Comment by ebraminio** [comment]
در دنیایی ایده‌آل باید به مرکزی که داده‌های تقویمی شما را نگه‌داری می‌کند گزارش دهید که توان ثبت به شمسی را در آن قرار دهد، حداقل از قابلیت‌های این برنامه توانایی اصلاح الگوریتم داده‌های ذخیره شده در گوگل نیست.

**Comment by r1ma952** [comment]
مثلا وقتی رو باید ثبت کنم، مثلا ۲۷ مهر، میرم معادل میلادی اش رو از پرشین کالندر در میارم وارد Todoist میکنم. قبلا مشکل نبود. الان هست. پس مجبورم تقویم کاغذی داشته باشم. راه دیگری هست؟ 
از گوگل کالندر استفاده نمیکنم برای درج رویداد ها. 
راه کار شما برای حل مشکل بنده چه هست؟ صمیمانه و متواضعانه سپاسگزارم

**Comment by ebraminio** [comment]
کاش راه‌حلی داشتم، شرمنده، ممنونم

**Comment by r1ma952** [comment]
ممنونم. پس باید یه تقویم کاغذی کنار پرشین کالندر داشته باشم. مرسی
