### ISSUE TITLE
پشتیبانی از smartspacer

### ISSUE THREAD

**Issue by luminax10** [persian-calendar/persian-calendar#1409]
درود و تشکر از برنامه فوق‌العاده تون.
لطفا پشتیبانی از smartspacer رو هم اضافه کنید.
Smartspacer برنامه‌ای برای جایگزین و بهبود ویجت at-a-glance گوگل هست و درصورت پشتیبانی، میشه باهاش (حداقل تو اندروید خام و نسخه‌های اوپن‌سورس) تقویم فارسی رو به صفحه قفل اضافه کرد.

**Comment by luminax10** [comment]
درسته، میشه از نوتیفیکیشن هم تاریخ رو دید، ولی اگه تاریخ همراه با ساعت باشه ظاهر بهتری داره و میون نوتیفیکیشن ها گم نمیشه.

**Comment by ebraminio** [comment]
سلام گرامی، فکر می‌کنم سال ۲۰۱۵ یا پیش از آن این برنامه پشتیبانی از DashClock داشت به همین دلیل ناآشنا با چنین ویژگی‌ی نیستم. من کمی وقت گذاشتم روی این موضوع که نتیجهٔ کارم اینجا است و https://github.com/persian-calendar/persian-calendar/compare/smartspace ولی مشخص شد برایم که minSdk این کتابخانهٔ ۲۹ است  

Suggestion: use a compatible library with a minSdk of at most 21, or increase this project's minSdk version to at least 29,

که هر چند من علاقه دارم که minSdk را بالا ببرم ولی می‌دانم کاربران بسیاری هم گوشی‌های قدیمیتری دارند و این ویژگی خود به تنهایی توجیه کافی برای عدم حمایت از آن دستگاه‌ها نیست که فکر می‌کنم برنامه‌ای جداگانه برای این موضوع بهتر باشد، با تشکر، ممنونم 😊
