### ISSUE TITLE
درخواست و اشکال

### ISSUE THREAD

**Issue by sepantanima** [persian-calendar/persian-calendar#1430]
سلام 
امکان بروز رسانی یا همون refresh  در برنامه بگذارید 
زمانی که تسک در Gmail می‌زنیم در برنامه شما دیده نمیشه  احتمالا نیاز به بازیابی و refresh داره  تا همگام بشه تسک ها 
همینطور وقتی تسک در برنامه شما میزنم در Gmail  اضافه نمیشه 
خلاصه همگام سازی به صورت دستی هم نیاز داریم در برنامه

**Comment by ebraminio** [comment]
سلام گرامی به نظر چنین راه‌حلی نیاز دارد https://stackoverflow.com/q/8036541 که نیاز به دسترسی خواهد داشت android.permission.GET_ACCOUNTS  که از آنجایی که در این برنامه سعی کرده‌ام از گرفتن دسترسی‌ها مختلف برای اطمینان کاربر تاجای ممکن پرهیز کنم (حتی تا به حال درباره‌ٔ دسترسی‌های فعلی هم شکایت داشته‌ام) به نظرم بهتر است طرف چنین کار و راه‌حلی نروم، ممنونم 😊

**Comment by sepantanima** [comment]
سلام
خب به هر حال نیاز داره
خب دسترسی رو اختیاری کنید کسی که لازم داره تایید بده
