### ISSUE TITLE
اعلام صوتی زمان باقی مانده تا غروب آفتاب به ویجت خورشید نما در تقویم فارسی

### ISSUE THREAD

**Issue by mohammasaeed2025** [persian-calendar/persian-calendar#1431]
با عرض سلام و احترام

در ویجت خورشید نما در نرم افزار تقویم فارسی، طلوع و غروب و طول روز و ساعات باقی مانده ی طول روز یا ساعات باقی مانده تا غروب خورشید به صورت نمودار نشان داده شده است.
با توجه به ویجت خورشید نما لطفاً در صورت امکان یک هشدار صوتی طول روز یا هشدار صوتی غروب آفتاب ایجاد کنید به طوری که از طلوع آفتاب تا غروب آفتاب هر یک ساعت یک دفعه زمان باقی مانده تا غروب آفتاب را به صورت صوتی اطلاع بدهد تا یاد آوری شود که تا چند ساعت دیگر هوا روشن است و روز است و تا چند ساعت دیگر زمان برای انجام کارهایمان داریم و تا شب نشده سریعتر کارهایمان را انجام دهیم.

مثال:
طول روز 12 ساعت و 8 دقیقه است
یک ساعت بعد از طلوع آفتاب به صورت صوتی اعلام کند: 11 ساعت تا غروب آفتاب
دو ساعت بعد از طلوع آفتاب به صورت صوتی اعلام کند: 10 ساعت تا غروب آفتاب
سه ساعت بعد از طلوع آفتاب  به صورت صوتی اعلام کند: 9 ساعت تا غروب آفتاب
چهار ساعت بعد از طلوع آفتاب به صورت صوتی اعلام کند: 8 ساعت تا غروب آفتاب
پنج ساعت بعد از طلوع آفتاب  به صورت صوتی اعلام کند: 7 ساعت تا غروب آفتاب
و ...
ده ساعت بعد از طلوع آفتاب به صورت صوتی اعلام کند: 2 ساعت تا غروب آفتاب
یازده ساعت بعد از طلوع آفتاب به صورت صوتی اعلام کند: 1 ساعت تا غروب آفتاب

و این ویژگی هم داشته باشد که بتوانیم انتخاب کنیم که مثلاً به صورت صوتی اعلام کند:
پنج
یا
پنج ساعت
یا
پنج ساعت تا غروب
یا
پنج ساعت مانده تا غروب آفتاب

بی نهایت تشکّر از زحمات شما و گروهتان برای نرم افزار رایگان تقویم فارسی
خیلی ممنون
خداحافظ

**Comment by ebraminio** [comment]
سلام گرامی نشد ولی حس می‌کنم برنامهٔ جداگانه برای آن مناسبتر باشد، منتهی بگویم حتی در آن برنامهٔ جداگانه سیستم‌عامل اندروید آنچنان نمی‌توان متعهد کرد که سرزمانی خاص کاری انجام دهد، چنین تعهدهایی هر روز در اندروید سختتر می‌شود همین است که بسیاری حتی نسبت به قابلیت اذان همین برنامه شاکی هستند ولی شاید بشود در برنامه‌ای جداگانه به گرفتن دسترسی‌های جداگانه چنین کاری کرد، ممنونم 😊
