### ISSUE TITLE
افزودن رویداد

### ISSUE THREAD

**Issue by Reza-Farahmand** [persian-calendar/persian-calendar#1436]
سلام
برای افزودن رویداد در پنجم هر ماه شمسی، به تقویم گوگل یا سامسونگ ارجاع داده میشم! با توجه به اختلاف تقویم شمسی و میلادی، در برخی ماه‌ها یکی دو روز اختلاف به وجود میاد که باعث میشه رویداد در تاریخ مد نظر یادآوری نشه!
آیا امکان اصلاح وجود داره؟

**Comment by ebraminio** [comment]
سلام گرامی، در این برنامه سعی بوده که دسترسی‌های کمتری جهت اطمینان کاربر گرفته شود به خاطر همین بعید می‌دانم در قالب این برنامه ممکن باشد، همچنین مشاهده فرمایید https://github.com/persian-calendar/persian-calendar/issues/803#issuecomment-2359380752 ممنونم
