### ISSUE TITLE
Error in event

### ISSUE THREAD

**Issue by hamlili6062** [persian-calendar/persian-calendar#1450]
داداش آذرگان میشه ۹ آذر

**Comment by ebraminio** [comment]
سلام گرامی این پیامتان را برای شخصی که این رویدادها را تدوین نهایی کرده فرستادم و ایشان در جواب مطلب مفصلی گفتند که با این پاراگراف شروع می‌شد:

> پیرامون تطبیق گاهشماری ایرانی با دیگر تاریخ‌های رایج توضیح مختصری لازم است که در ادامه عرض می‌کنم، در گذشته تمامی ۱۲ ماه سال سی روزه بوده و پنج روز باقی مانده از سال بنام پنجه در انتهای سال بشکل جداگانه قرار می‌گرفته، به این دلیل برای اردیبهشت یک روز، خرداد دو روز، تیر سه روز الی مهر ماه که به شش روز می‌رسد، تقدم تاریخی وجود دارد و این تغییر تا فروردین ماه سال بعد در هر ماه اعمال می‌شود، بعنوان مثال، جشن شب چله یا یلدا مربوط به واپسین روز آذر ماه بنام انارم روز است، در گاهشماری ایرانی برابر با ۲۴ آذر گاهشماری خورشیدی است اما به دلیل ۶ روز جابجایی آنرا سی ام آذر ماه خورشیدی برپا می‌کنند. نکته ای هست که یادآور می‌شوم، در دی ماه ۴ جشن دی گان برپا می‌شود بنابراین متن دارای ایراد نگارشی نیست.

اگر پیام دیگری دارید می‌توانم برایشان ارسال کنم یا اگر مایل بودید مستقیم با ایشان صحبت کنید، ممنونم 😊
