### ISSUE TITLE
Syncing with other apps (Trello, Todoist, ...) 

### ISSUE THREAD

**Issue by Alofte** [persian-calendar/persian-calendar#1457]
سلام، وقتتون بخیر. آیا امکان سینک شدن تقویم با برنامه هایی مثل ترلو یا تودوایست و امثالهم وجود داره ؟
چون نقطه ی خرید پرمیوم این برنامه ها در نمایش تسک ها روی تقویم هستش و خود این برنامه ها امکان سینک شدن با برنامه هایی مثل Google Calendar رو دارند و تقویم جلالی نبودش حس میشه.
فکر میکنم از طریق اکستنشن های این نرم‌افزار ها بشه چنین لینکی برقرار کرد بین شما و اون برنامه. یا از API که خود نرم‌افزار برای دسترسی به حساب و تسک ها میده. یا از طریق فایل iCal که سابسکریبشنی هستش که در حالت Read only اطلاعات رو به صورت مستمر در اختیار تقویم ها قرار میده، لینک این موضوع رو هم جهت اطلاعات بیشتر قرار میدم:
https://todoist.com/help/articles/add-a-todoist-calendar-feed-pAk3tk
ممنون از وقتتون، خوشحال میشم اگه بتونم در این زمینه کمکی بکنم.

**Comment by ebraminio** [comment]
سلام گرامی قبلاً سعی کردم که تلاشی با Todoی گوگل داشته باشم ولی راهی پیدا نکردم که دسترسی‌های بیشتر از جمله اینترنت نگیرد، وابستگی به کتابخانه‌های گوگل پلی ایجاد نکند و حجم را هم زیاد بالا نبرد چرا که این‌ها جز معیارهای توسعهٔ این برنامه از ابتدا بوده‌اند ولی پیشنهادتان قطعاً در قالب یک برنامهٔ تقویم معقول است ولی شاید در این پروژه ممکن نباشد.
