### ISSUE TITLE
درخواست اضافه کردن قابلیت برای افزودن رویداد در خود برنامه

### ISSUE THREAD

**Issue by BLAZE-English** [persian-calendar/persian-calendar#1462]
لطفاً در خود برنامه بدون نیاز به google calender قابلیت رویداد را اضافه کنید.

**Comment by ebraminio** [comment]
سلام گرامی پس از ثبت نیاز به backup و خواندن از آن خواهد داشت و این قابلیت‌ها یا نیازمند دسترسی خواندن از حافظه دارند یا دسترسی به اینترنت به همین دلیل با اینکه درخواست بسیار درست معقول بعید می‌دانم در این پروژه ممکن باشد 😕
