### ISSUE TITLE
انتقاد و پیشنهادی موثر و کاربردی 

### ISSUE THREAD

**Issue by Arsamofa** [persian-calendar/persian-calendar#1470]
درود برشما دوست عزیز؛
    در رابطه با ایکون برنامه [تقویم فارسی] نظرم بر این بود که اگر امکانش هست اعلان عددی تاریخ روز داخل آیکون برنامه درج کنید  منظورم در حال حاظر که رو آیکون، عدد ۲۹ به صورت ثابت هست این عدد متغیر به روز تعویض یا تغییر در شمایل آیکون برنامه بشود. 
این یک پیشنهادی کوچک از روند برنامه بسیار کامل تون دارم بلکه باعث رضایت بیشتر کاربران باشه .
باتشکر فراوان.

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید، دچار چالش‌هایی که در #932 به خاطر همین این ایشو را با آن ادغام می‌کنم، ممنونم 😊
