### ISSUE TITLE
رویداد روز مادر

### ISSUE THREAD

**Issue by mansourdiarmand** [persian-calendar/persian-calendar#1471]
سلام در تقویم شما روز مادر در ۲ دی ماه ۱۴۰۳ به عنوان رویداد اون روز وجود نداره !!!!!!!!
یعنی چی . تازه آخرین آپدیت رو هم نصب کردم

**Comment by ebraminio** [comment]
سلام گرامی لطفاً از تنظیمات رویدادهای غیرتعطیل را فعال کنید، برنامه همان ابتدا دربارهٔ رویدادهای مورد نظرتان از شما می‌پرسد و پیش‌فرض آن رویدادها تعطیل است. ممنونم
