### ISSUE TITLE
Wrong show year view on drag to down.

### ISSUE THREAD

**Issue by Developer-N** [persian-calendar/persian-calendar#1473]
https://github.com/persian-calendar/persian-calendar/blob/a0f22ab8600357a6c8a2c3780d875c33416a2460/PersianCalendar/src/main/kotlin/com/byagowi/persiancalendar/ui/calendar/CalendarScreen.kt#L330

it is must be like this ->
...
 } else if (wasAtTop **&& dragAmount > 0**) {
....

**Comment by ebraminio** [comment]
با تشکر اصلاح شد 😊

**Comment by Developer-N** [comment]
خواهش میکنم موفق باشید 😊🌸
