### ISSUE TITLE
Father day

### ISSUE THREAD

**Issue by shahram-hosseini** [persian-calendar/persian-calendar#1474]
با سلام، چرا برای روز پدر، در روز 26 دی ماه رویداد گذاشتید؟

**Comment by shahram-hosseini** [comment]
برای روز 25 دی نوشته اید ولادت امام علی، و برای روز 26 ام نوشته اید روز پدر !

**Comment by ebraminio** [comment]
سلام گرامی، به نظر که با تقویم مرکز تقویم هماهنگ است

https://calendar.ut.ac.ir/documents/2139738/7092644/Calendar-1403.pdf

<img width="750" alt="image" src="https://github.com/user-attachments/assets/05e99684-2943-44c1-8ec1-df13718a4494" />

<img width="310" alt="image" src="https://github.com/user-attachments/assets/a6b4c09d-9931-428e-af16-d3323e72aeb2" />

**Comment by shahram-hosseini** [comment]
![Screenshot_20241229-173159_Persian Calendar](https://github.com/user-attachments/assets/87ba7a36-3f2b-4875-8be0-679b2ab34217)
![Screenshot_20241229-173151_Persian Calendar](https://github.com/user-attachments/assets/d4a3bd96-759f-492a-9c1f-d177c0397b01)

**Comment by ebraminio** [comment]
سلام گرامی، عکس

**Comment by ebraminio** [comment]
سلام گرامی آن مناسبت سبز از تقویم فارسی نیامده از تقویم دستگاه آمده است، امکان در پنجرهٔ رویدادها در تنظمیات روزهای غیرتعطیل تقویم رسمی ایران را فعال کنید؟ ممنونم

**Comment by shahram-hosseini** [comment]
خیلی لطف کردید، در منوی تنظیمات دو تا تغییر طبق شکل پیوست دادم و درست شد (گذاشتن تیک سایر مناسبتهای ایران و برداشتن تیک holiday in iran
![Screenshot_20241230-092858_Persian Calendar](https://github.com/user-attachments/assets/935072ac-0b04-483c-894b-ad85829d83ac)
![Screenshot_20241230-093101_Persian Calendar](https://github.com/user-attachments/assets/c0cfab31-8137-4fa4-9593-281aac83a37b)
)
