### ISSUE TITLE
درخواست راهنمایی

### ISSUE THREAD

**Issue by dagithubun** [persian-calendar/persian-calendar#1475]
سلام. ابتدا تشکر می‌کنم بابت توسعه‌ی چنین برنامه‌ی فوق‌العاده‌ای. حقیقتا ممنون.

راستش من خیلی دوست دارم در توسعه‌ی این برنامه سهیم بشم. شما منابع خاصی مدنظرتون هست برای شروع یادگیری کاتلین و compose؟ آیا شدنی هست صرفا با code base پروژه‌ی شما این دو مقوله رو یاد بگیرم و مشارکت کنم؟

ممنون میشم

**Comment by ebraminio** [comment]
سلام گرامی، ممنونم بابت لطفتان 😊 واقعیت منبع خاصی نمی‌شناسم، شاید فیلم‌های آموزشی خوبی در این رابطه بتوان پیدا کرد، برای آشنایی بهتر توصیهٔ شخصی‌ام این است که پروژهٔ خودتان را مثلاً در موضوعی دیگر که کمبود آن را خود به‌عنوان کاربر حس می‌کنید یا حتی یک بازی ساده که ساده‌ترین شکل آنچه که مورد نظرتان است باشد، پس از آن هر روز آن را بهینه‌تر کرده تا به حدی برای دیگران مفید باشد، تازگی‌ها https://github.com/amir1376/ab-download-manager را هم دیده‌ام واقعاً پروژه خوب و مفیدی بود گفتم آن را به شما معرفی کنم بابت ایده‌هایی که می‌توان برای یک برنامهٔ خوب و محبوب و جدید داشت، ممنونم 😊

**Comment by ebraminio** [comment]
البته البته بگویم همیشه هم می‌توانید اگر مایل باشید در این پروژه مشارکت داشته باشید یا اگر چیزی به ذهنتان یک فایل جدید باز کنید حتی بدون اینکه لازم باشد کدی بنویسید ولی منظور من این بود که بهترین راه برای یادگیری که به همان میزان برای خودتان مفید باشد را پروژه‌ای نو و از پایه و جدید می‌دانم که بتوانید ذره ذره آن و توانایی خودتان را بهبود دهید، اگر چنین کردید می‌توانید لینک آن را همینجا قرار دهید که من یا دیگرانی که اینجا را می‌بینند بتوانند در آن مشارکت کنند، باز هم ممنونم 😊

**Comment by dagithubun** [comment]
دست گلتون درد نکنه بابت زحماتتون برای این پروژه. لطف کردید. سپاس از راهنمایی‌های مفید شما❤️

**Comment by amir1376** [comment]
> سلام گرامی، ممنونم بابت لطفتان 😊 واقعیت منبع خاصی نمی‌شناسم، شاید فیلم‌های آموزشی خوبی در این رابطه بتوان پیدا کرد، برای آشنایی بهتر توصیهٔ شخصی‌ام این است که پروژهٔ خودتان را مثلاً در موضوعی دیگر که کمبود آن را خود به‌عنوان کاربر حس می‌کنید یا حتی یک بازی ساده که ساده‌ترین شکل آنچه که مورد نظرتان است باشد، پس از آن هر روز آن را بهینه‌تر کرده تا به حدی برای دیگران مفید باشد، تازگی‌ها https://github.com/amir1376/ab-download-manager را هم دیده‌ام واقعاً پروژه خوب و مفیدی بود گفتم آن را به شما معرفی کنم بابت ایده‌هایی که می‌توان برای یک برنامهٔ خوب و محبوب و جدید داشت، ممنونم 😊

درود @ebraminio جان، همین الان داشتم توی گیتهاب می‌چرخیدم و پیامتو دیدم 😊  
خیلی خوشحال شدم که پروژه مفید واقع شده 🌹 امیدوارم برای بقیه هم الهام‌بخش باشه 🙏
و اینکه مرسی که پروژه رو به بقیه عزیزان هم معرفی کردی.❤️
خیلی دوست دارم یه روز با هم همکاری کنیم

**Comment by ebraminio** [comment]
حتماً گرامی هر دو بزرگوار اگر مایل بودید می‌توانید به تلگرام من با همین آی‌دی پیام دهید 😊
