### ISSUE TITLE
تغییر تاریخ جشن‌های ایرانی و مناسبت‌های زرتشتی

### ISSUE THREAD

**Issue by amirrezaeng** [persian-calendar/persian-calendar#211]
با سلام
از تقویم خیلی خوبتون تشکر می‌کنم. نکته‌ای که باید در ارتباط با مناسبت‌های باستانی ایران و زرتشتی به آن توجه کرد اینست که ما در تقویم جلالی فعلی، ۶ ماه اول سال را ۳۱ روزه در نظر می‌گیریم و ماه‌های نیمه دوم سال را ۳۰ روزه (غیر از اسفند) که با تقویم باستانی ایران کمی متفاوت است. در تقویم باستانی و حتی زمان ساسانیان تمام ماه‌ها ۳۰ روزه بوده و در آخر سال ۵ 
 روز را با نام «پنجه دزدیده یا اندرگاه» به پایان سال اضافه می‌کردند و ساله‌های کبیسه هم ۶ روز و البته در زمان ساسانیان هر ۱۲۰ سال را کبیسه می‌گرفتند که یک ماه به سال افزوده می‌شد. حال با این وصف جشن خردادگان که شما آن را در روز  ۶ خرداد گاهشمارتان درج کرده‌اید، در واقع روز ۶ ماه «هه اروتات» (خورداد) تقویم زرتشتی است و نه گاهشمار فعلی و باید در روز   ۴ خورداد تقویم درج شود. حالا این را به سایر مناسبت‌ها نیز تعمیم دهید (از ماه فروردین به بعد) مثلاً جشن مهرگان که در تقویم زرتشتی روز ۱۶ مهر است، باید در تقویم جلالی فعلی در ۱۰ مهر درج شود. البته می‌توان جشن‌های که مرجع مشخصی را ندارند یا بعد از تقویم خیام (جلالی) پدید آمده‌اند؛ (مانند ارغاسوان) را از این قاعده مستثنی کرد چون آغاز پیدایش آن‌ها مشخص نیست و در واقع مردمی هستند و نه آئینی و الزاماً بر اساس تقویم زرتشتی نیستند. نکته دیگر اینکه؛ نام ماه سوم به «خورداد» و نام ماه پنجم به «اَمُرداد» تغییر کند، زیرا «مرداد» نادرست است و به معنی «مرگ» و «اَمُرداد» درست آن؛ و به معنی جاودانه و بی‌مرگی است. همچین شایسته است؛ نام روزهای ماه‌های ایرانی بر اساس تقویم زرتشتی نیز در تقویم‌تان درج شود، همانگونه که می‌دانید ۳۰ روز ماه در تقویم باستانی هر یک نامی دارند که اگر اشتباه نکنم در تقویم «سال» از گروه «مگاپیل» درج شده است که سال‌های قبل در یکی دو مورد اشتباه هم در آن دیدم. همچنین سال زرتشتی را نیز می‌توان به گاهشمار افزود نمود که امسال ۳۷۵۶ زرتشتی است. برای گاهشمار خوبتان می‌توانید از سایت زیر هم بهره ببرید
http://dinebehi.com/gahshomar.htm
با سپاس فراوان

**Comment by ebraminio** [comment]
سلام امیررضا جان، مطالب بسیار جالبی بودند، مناسبت‌ها در حقیقت از تقویم دیگری گرفته شده‌اند و من چندان تخصصی در رابطه با آن‌ها ندارم، تغییری اگر به ذهنتان می‌رسد دیگر می‌توانید مستقیم خود در 
https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/src/main/res/raw/events.json
اعمال کنید و برای پروژه ارسال کنید تا بازبینی و در نهایت اعمال شود. ممنون از شما :)

**Comment by behdad222** [comment]
اگر بخوایم اینا رو به شکل درست اعمال کنیم باید علاوه بر شمسی و قمری و میلادی تقویم مربوطه رو هم داشته باشیم
و ایونت‌های مربوطه رو همون تقویم باشه مثل قمری و میلادی

**Comment by amirrezaeng** [comment]
سلام
من در زمانی که آن پیام را برای اصلاح تاریخ و مناسبت‌های ایرانی دادم، وقت چندانی برای اصلاح توسط خودم نداشتم و هنوز تقویم تصحیح نشده، لینکی که در بالا ارسال کردید کار نمی‌کند. چطور می‌توانم اصلاحات را الان انجام دهم.
ممنون

**Comment by ebraminio** [comment]
در حال حاضر اینجا قرار دارد :)

https://github.com/persian-calendar/DroidPersianCalendar/blob/main/PersianCalendar/data/events.json#L813

**Comment by ebraminio** [comment]
ولی حرف بهداد هم در رابطه به نیاز به پیاده‌سازی تقویمی دیگر به این منظور بسیار منطقی است، به نظرم اصلاح را در چند مرحله داشته باشیم و اول آنچه که نیاز به تقویمی جداگانه ندارد، عنوان یا تغییری کوچیک مشکل را برطرف می‌کند انجام دهیم تا بعداً ببینیم چه می‌شود، ممنون :)

**Comment by amirrezaeng** [comment]
سلامکاملاً موافقم. شما بفرمایید از کجا شروع کنیم. من مناسبتها را برای ۱۴۰۰ استخراج کرده‌ام و همچنین نظام نام‌گذاری روزها در گاهشمار زرتشتیOn Oct 6, 2021 1:06 AM, ebraminio ***@***.***> wrote:
ولی حرف بهداد هم در رابطه به نیاز به پیاده‌سازی تقویمی دیگر به این منظور بسیار منطقی است، به نظرم اصلاح را در چند مرحله داشته باشیم و اول آنچه که نیاز به تقویمی جداگانه ندارد، عنوان یا تغییری کوچیک مشکل را برطرف می‌کند انجام دهیم تا بعداً ببینیم چه می‌شود، ممنون :)

**Comment by ebraminio** [comment]
در نسخهٔ جدید این اصلاحات انجام شده، بررسی فرمایید، ممنون 😊

**Comment by amirrezaeng** [comment]
سلام قربان
ممنون
لطف فرمودید
طبق فرمایش شما بررسی می‌کنم
پیروز باشید همیشه

**Comment by amirrezaeng** [comment]
درود بر شما
از کوشش‌ها و مهر شما سپاسگزارم. جملگی مناسبت‌ها در نسخه جدید گاهشمار درست شده‌اند.

مهر و خرد ایزدی همواره یارتان
امیررضا رشیدفرخی
