### ISSUE TITLE
Add option to set interface font in themeing options

### ISSUE THREAD

**Issue by rezazoom** [persian-calendar/persian-calendar#370]
#suggestion User may change font of their calendar by selecting a ttf file from mobile directories, I'd like to have a Persian calendar with a persian font really! or you can preset a set of free fonts in the app for a better -clean- looking UI and widgets, it can be free fonts like Shabnam or Vazir from github.com/rastikerdar

**Comment by ebraminio** [comment]
اوه انتخاب فونت دردسرش این می‌شه که دسترسی اس‌دی کارت می‌خوات که ما می‌خواستیم دسترسی نگیریم کاربرا مطمئن‌تر باشن به چیزی که نصب می‌کنن، باید به فونت جایگزین ولی فکر کنیم حتماً

**Comment by rezazoom** [comment]
شرمنده من زیاد از توسعه‌ اندروید نمی‌دونم ولی نمیشه فقط وقتی دایلوگ انتخاب فونت باز میشه دسترسی درخواست بشه؟ مثل اپ تلگرام که برای عکس انداختن بعداز اینکه روی آیکون دوربین کلیک میکنی واسه پرمیژن سوال میکنه.
خلاصه اگه سمت فونت میخواید برید من این لیست رو پیشنهاد میدم:

وزیر

**Comment by ebraminio** [comment]
تاجایی که می‌دونم (از روی تجربه‌م با جی‌پی‌اس) نه، باشه بررسی می‌کنم وزیر
رو :)

**Comment by alirezaivaz** [comment]
الان فونت نسخ که به‌صورت پیش‌فرض نصبه، فارسی نیست و به‌قول جدیدی‌ها خز شده :) هیچ ظاهر خوبی ندارد و چشم رو خسته می‌کنه. من وزیر رو امتحان کردم ولی باید حتما سایز متن‌های برنامه تغییر داده بشن.

**Comment by ebraminio** [comment]
اولین مشکلی که داشت وزیر که همه زبان‌هایی که ما پشتیبانی می‌کنیم رو پشتیبانی نمی‌کنه که یه ایشو هم در ریپوشان باز کردم

**Comment by ebraminio** [comment]
با تشکر، ادغام در #527 😊
