### ISSUE TITLE
ادغام تب تقویم و مناسبتها

### ISSUE THREAD

**Issue by panevesht** [persian-calendar/persian-calendar#440]
جدا بودن تب‌های تقویم و مناسبتها باعث شده که تمرکز بر روی تقویم باشد و استفاده از بخش مناسبتها مشکل باشد. پیشنهاد:
تب‌های تقویم و مناسبتها ادغام شوند. در این صورت فضای بالا آزاد میشود.
در ادامه ابتدا بخش تقویم نمایش داده میشود و زیر آن فهرست مناسبتها همه در یک صفحه.
حتی بخش تقویم می تواند کمی فشرده تر باشد.

**Comment by ebraminio** [comment]
سلام! اگر تب تقویم و مناسبت‌ها ادغام شوند در حالت عدم وجود اوقات شرعی کلاً یک تب خواهیم داشت و تب باید پاک شود و اگر اوقات شرعی تنظیم شده باشد تب باید برگردد و کمی پیچیده می‌شود :/ درست می‌فرمایید وضعیت فعلی خصوصاً در صفحه‌های بزرگتر جای بهبود دارد

**Comment by panevesht** [comment]
سپاس از شما،
پس کاش تب پیش‌فرض رو بشه از تنظیمات انتخاب کرد. اونوقت منی که بیشترین
استفاده م رخداد‌های کلندر هست، می‌تونم تب مناسبت‌ها رو بعنوان پیشفرض انتخاب
کنم :)

**Comment by ebraminio** [comment]
الآن اینگونه است که چیزی که دفعهٔ قبل باز شده بوده را ذخیره می‌کند، به آن شکل مفید نبوده است؟

**Comment by panevesht** [comment]
چرا. خیلی خوبه. من نمی‌ دونستم این فیچر رو داره. ممنون :)

**Comment by ebraminio** [comment]
با تشکر از شما گرامی 😊
