### ISSUE TITLE
فونت یکان برای ویجت

### ISSUE THREAD

**Issue by habibnajafi** [persian-calendar/persian-calendar#462]
سلام فونت یکان برای ویجت ها اگر میتونستین به کار ببرید خیلی عالی میشد همچنین پس زمینه با قابلیت شفافیت قابل تنظیم هم براش بذارید که زیبا بشه ممنون

**Comment by ebraminio** [comment]
تنظیم فونت برای ویجت دردسر است و مشکل کارایی دارد آن فونتی که مجوز خوب از آن نداریم... برای قابل تنظیم بودن شفافیت ویجت، حق دارید

**Comment by habibnajafi** [comment]
من با کمک زوپر و تقویم فارسی یه ویجت ساختم
http://s5.picofile.com/file/8369965642/Screenshot_2019_08_18_20_02_59.png
اگر تقویم فارسی همچین ویجتی داشت عالی بود

**Comment by ebraminio** [comment]
طرج زیبایی بود برای ویجت، ممنون

**Comment by alirezaivaz** [comment]
سلام. اگه قراره از فونت استفاده بشه، به‌نظرم وزیر یکی‌از بهترین‌هاست؛ هم متن‌بازه، هم ظاهر تر و تمیزی داره، هم فارسیه؛ ولی یکان نه متن‌بازه، نه ظاهر خوبی داره و نه فارسیه!

**Comment by ilius** [comment]
من فونت شبنم رو به همه ترجیح میدم.
از لحاظ زیبایی و خوانایی و مجوز.

**Comment by ebraminio** [comment]
با تشکر، ادغام در #527 😊
