### ISSUE TITLE
اشکال در پخش اذان

### ISSUE THREAD

**Issue by martyr72** [persian-calendar/persian-calendar#523]
به نام خدا
سلام. قبلاً در ایشوی #419 
اشکال در پخش اذان رفع شده است و در نسخه جدید این مشکل وجود ندارد ولی در نوکیا 6.1 و اندروید 9 با پخش اذان، میزان بلندی صدای هشدار یا نوتیفیکیشن هر مقداری که باشد، صفر می‌شود و مثلاً در صورت دریافت پیامک یا ایمیل جدید، صدای اخطاری از طرف گوشی نمی‌آید

موفق و پیروز باشید

**Comment by martyr72** [comment]
تشکر

**Comment by ebraminio** [comment]
شرمنده نمی‌دونم چطور پیامتونو ندیدم، ممنونم :)
