### ISSUE TITLE
چند پیشنهاد برای جایگزینی تصویر اذان

### ISSUE THREAD

**Issue by martyr72** [persian-calendar/persian-calendar#539]
به نام خدا
با سلام و تبریک سال جدید و آرزوی سلامتی و نابودی این ویروس از کل جهان
چند پیشنهاد برای جایگزینی تصویر هنگام پخش اذان ارائه می دهم تا در صورت صلاحدید آن را جایگزین کنید.

تصویر اول [https://rasekhoon.net/photogallery/show/1383607/%D9%BE%D9%88%D8%B3%D8%AA%D8%B1-%D8%A7%D9%85%D8%A7%D9%85%D8%B2%D8%A7%D8%AF%DA%AF%D8%A7%D9%86-%DA%AF%D9%84%D8%AF%D8%B3%D8%AA%D9%87-%D9%87%D8%A7%DB%8C-%D8%A7%D9%85%D8%A7%D9%85%D8%B2%D8%A7%D8%AF%D9%87-%D9%84%D8%A7%DB%8C%D9%87-%D8%A8%D8%A7%D8%B2](url)

تصویر دوم
[http://wisgoon.com/pin/507882/](url)

تصویر سوم
[https://fa.m.wikipedia.org/wiki/%D9%BE%D8%B1%D9%88%D9%86%D8%AF%D9%87:Twemoji2_1f54c.svg](url)

تصویر چهارم
[http://www.piksell.ir/2925/%D9%88%DA%A9%D8%AA%D9%88%D8%B1-%D9%84%D8%A7%DB%8C%D9%87-%D8%A8%D8%A7%D8%B2-%D8%AE%D8%B7%DB%8C-%DA%A9%D8%B9%D8%A8%D9%87-%D9%88-%D9%85%D8%B3%D8%AC%D8%AF-%D8%A7%D9%84%D9%86%D8%A8%DB%8C](url)

تصویر پنجم 
[https://clipartstation.com/wp-content/uploads/2018/10/mecca-madina-clipart-3.jpg](url)

موفق و سلامت باشید
4 فروردین 1399

**Comment by ebraminio** [comment]
سلام گرامی، از ان موقع تصاویر اذان‌ها با طرحی متحرک جایگزین شده است، امیدوارم راضی کننده باشد :)
