### ISSUE TITLE
امکان تغییر فونت فارسی

### ISSUE THREAD

**Issue by ahmaduxui** [persian-calendar/persian-calendar#592]
برای بهتر شدن رابط کاربری برنامه بهتره در کنار فونت پیشفرض فعلی چندتا فونت آزاد فارسی هم اضافه کنید مثل فونت وزیر، شبنم، استعداد، صمیم و میخک.

**Comment by ahmaduxui** [comment]
فونت وزیرمتن و استعداد گزینه‌های خوبی برای افزودن برنامه هستند

**Comment by ebraminio** [comment]
با تشکر، ادغام در #527 😊
