### ISSUE TITLE
آیکون داینامیک

### ISSUE THREAD

**Issue by AryanAhadinia** [persian-calendar/persian-calendar#654]
میشود که آیکون داینامیک باشد، به این صورت که به جای نمایش ثابت عدد 29 در آیکون، تاریخ همان روز نشان داده شود. در اپلیکشن هایی مانند تقویم سامسونگ این اتفاق می افتد

**Comment by ebraminio** [comment]
اگه می‌شد عالی می‌شد واقعاً و بهترین ویجتمان می‌بود ولی حداقل تا بررسی که اینجا کرده بود یکی از دوستان
https://blog.farnasirim.com/2018/08/dynamically-changing-android-app-icons.html
ظاهراً حداقل راه رسمی ندارد :/

**Comment by AryanAhadinia** [comment]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
به نظر میاد این قابلیت اضافه شده

**Comment by ebraminio** [comment]
از این قابلیت اندروید ۱۳ در حال حاضر استفاده می‌کنیم 
<img width="444" alt="image" src="https://user-images.githubusercontent.com/833473/206799077-bd7845f3-2639-4c71-a759-5e7c45df95eb.png">
ولی از آن موقع تا به حال یاد گرفته‌ام که این قضیه راه‌حلی داشته فقط کمی ترسناک است

https://github.com/persian-calendar/persian-calendar/compare/dynamic-icons

**Comment by ebraminio** [comment]
از لینکی که محبت کردید، آن قسمت For dynamic shortcuts, call the createWithAdaptiveBitmap() method when you create them را نمی‌دانم کی صدا بزند فکر می‌کنم فقط دفعهٔ اول که می‌خواهد آیکون را قرار دهد؟

**Comment by ebraminio** [comment]
با تشکر، ادغام با #932
