### ISSUE TITLE
تغییر فونت ویجت

### ISSUE THREAD

**Issue by ahmadhosein** [persian-calendar/persian-calendar#734]
با سلام و تشکر از برنامه خوبتان
لطفا در تنظیمات ویجت، امکان تغییر فونت و بولد نمودن را اضافه بفرمایید
با تشکر

**Comment by ebraminio** [comment]
ممنونم احمد جان، کمی دردسر دارد ولی نشد نیست ببینیم در انتشارهای بعد چه کارهای می‌توانیم انجام دهیم، ممنونم :)

**Comment by ebraminio** [comment]
با تشکر، ادغام در #527 😊

**Comment by sam2007-droid** [comment]
چون بسته شده کامنتم را در پست   [فونت پیش‌فرض تقویم](https://github.com/persian-calendar/persian-calendar/issues/527#top)
#527 گذاشتم
