### ISSUE TITLE
consider lunar tilt rotation degree in moon view

### ISSUE THREAD

**Issue by ebraminio** [persian-calendar/persian-calendar#825]
see https://twitter.com/CHEMENG_MHMD/status/1476350063416946696 for context

**Comment by ebraminio** [comment]
Some works are done https://github.com/persian-calendar/DroidPersianCalendar/commit/864ecda839c102a9931ebf6730e65a874f8aa5a1 here, yet to do more :)

**Comment by ebraminio** [comment]
Also maybe considering its libration also https://en.wikipedia.org/wiki/Libration

**Comment by cosinekitty** [comment]
FYI, I will have libration calculation soon in the Kotlin version of Astronomy Engine.

**Comment by ebraminio** [comment]
You know, all the things have actually started from this tweet https://twitter.com/CHEMENG_MHMD/status/1476350063416946696

We had a moon view in https://twitter.com/behdad222/status/1472915087878987780 which didn't consider for sunlit angle and that tweet was suggesting we better need to consider it. 

I was initially have confused libration with moon sunlit angle so now thanks to your help here https://github.com/cosinekitty/astronomy/issues/144 we now have:

https://user-images.githubusercontent.com/833473/162806062-24d58f71-3bd1-4d7d-b839-c6ce33149ea2.mov

Now the problem is if I consider for the same suggested place its animation will be far from pleasing:

https://user-images.githubusercontent.com/833473/162808381-ef510fe5-1fc3-4ebe-8e2b-f1fc951921f8.mov

which is understandable but well this isn't really main offerings of the app so I can just go without having exact sunlit tilt that on the main calendar screen but just in compass screen which looks great enough! Unless you got some other ideas.

Thank you very much! :)
