### ISSUE TITLE
درخواست افزایش فاصله بین خطوط در ویجت

### ISSUE THREAD

**Issue by Mahantor** [persian-calendar/persian-calendar#877]
سلام
لطفا فاصله بین خطوط را در‌ ویجت بیشتر کنید بیشتر اوقات اعداد و حروف در هم تنیده می شوند
![IMG_20220223_160313](https://user-images.githubusercontent.com/91434001/155320737-e3623d5d-aaa4-4236-baf2-c9bb7945faa9.jpg)

**Comment by ebraminio** [comment]
سلام گرامی ظاهراً تازه این ایشو را دیدم واقعیت در شبیه‌ساز اینگونه دیده می‌شود

<img alt="image" src="https://user-images.githubusercontent.com/833473/163949917-ec717d2e-cae3-44ca-a525-ca0b1183bcc0.png">

می‌ترسم تغییری دهم و اوضاع را بدتر کنم :/

**Comment by ebraminio** [comment]
فکر می‌کنم به شیوه‌ای فونت سیستم را تغییر داده‌اید؟
