### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fateme13790909** [persian-calendar/persian-calendar#884]
اذان گو مشکل داره.
هر زمان  بخواد پخش می شه 
بعضی وقتا راحت قطع می شه و بعضی وقتا با هزار سلام صلوات قطع می شه

**Comment by ebraminio** [comment]
گوشی‌ها متأسفانه با هم تفاوت زیادی دارند و به تجربه‌ام وقتی اذان کار نکند کار زیادی هم نمی‌شود کرد، ممنون :)
