### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by Developer-N** [persian-calendar/persian-calendar#891]
https://github.com/persian-calendar/persian-calendar/blob/cd1c01fc3c27c7afb478e418f0a0fed2d4be58e1/gradlePlugins/src/main/java/io/github/persiancalendar/gradle/CodeGenerators.kt#L42

A problem was found with the configuration of task ':PersianCalendar:codegenerators' (type 'CodeGenerators').
  - In plugin 'io.github.persiancalendar.appbuildplugin' type 'io.github.persiancalendar.gradle.CodeGenerators' property 'generatedAppSrcDir' specifies directory 'E:\WorkSpace_2022\Android\DroidPersianCalendar\PersianCalendar\build\generated\source\appsrc\main' which doesn't exist.

**Comment by ebraminio** [comment]
ممنون بابت گزارش، شاید با https://github.com/persian-calendar/persian-calendar/commit/ec434f55a2260d3e0adb4b92e55a5b00817baa6d کمی بهتر شود

**Comment by Developer-N** [comment]
![1234](https://user-images.githubusercontent.com/34347784/156060019-c67894cf-ec49-4eca-9a12-cb95236f2db7.png)
هنوز هم مشکل بیلد رو دارم و یه مشکل عجیب دیگه :| 
دلیلش چیه؟

**Comment by ebraminio** [comment]
چه عجیب، حتی java.io.File رو نمی‌شناسه، نمی‌دونم الآن چیزی به ذهنم نمی‌رسه :/

**Comment by Developer-N** [comment]
جالبه وقتی که RUN(Shift+F10) رو میزنم بیلد با موفقیت انجام میشه و برنامه بدون هیچ مشکلی اجرا میشه ولی وقتی  از منوی Build گزینه Rebuild Project  رو میزنم باز همون ارور هست.
کماکان مشکل File پابرجاست  شاید مشکل از اندروید استودیوی منه البته چندین بار هم کش رو پاک کردم و ریستارت کردم ولی هنوز حل نشده :|

**Comment by Developer-N** [comment]
![Screenshot from 2022-03-09 20-28-47](https://user-images.githubusercontent.com/34347784/157491937-5ec4e25e-f9e7-4b45-8c6b-51e5bd28aad5.png)
 رفتم اوبونتو نصب کردم باز هم همون ارور بیلد وجود داره ولی اینجا مشکل ویندوز که فایل رو هم نمی شناخت ندارم.

**Comment by ebraminio** [comment]
فکر می‌کردم با یک سیستم جدید مشکل برطرف شود، واقعاً نمی‌دونم :/ اگه تو کامند همین پوشه در ترمینال بنویسید

./gradlew assembleMinApi17Nightly

آیا باز هم همین مشکل را خواهد داشت؟

**Comment by Developer-N** [comment]
اینا رو امتحان کردم با موفقیت بیلد انجام شد هر ۳ مورد. :))
./gradlew assembleMinApi17Nightly
./gradlew assembleMinApi21Nightly
 ./gradlew assembleMinApi17Debug
ولی بازاز منوی Build گزینه Rebuild Project رو بزنم ارور رو دوباره نشون میده. :|

**Comment by ebraminio** [comment]
اگر به نتیجه‌ای رسیدید ما رو هم مطلع کنید، ممنون :)
