### ISSUE TITLE
عدم بیلد شدن 

### ISSUE THREAD

**Issue by wixller** [persian-calendar/persian-calendar#910]
![Screenshot (231)](https://user-images.githubusercontent.com/102912767/161433643-26c99be7-5975-43e2-bce2-2401ef8ea419.png)

سلام برنامه برای اولین بار ایمپورت کردم و هنگام بیلد این ارور هارو میده و بیلد نمیشه

**Comment by ebraminio** [comment]
سلام، باید گیت در سیستم نصب باشد :)

**Comment by wixller** [comment]
![Screenshot (232)](https://user-images.githubusercontent.com/102912767/161451976-0b397567-31b2-40e7-8ed0-4e29953522f8.png)


نصب کردم، دوباره کلون کردم،  بازم ارور میده ممنون میشم راهنمایی کنید

**Comment by ebraminio** [comment]
آیا در cmd بنویسید git خود برنامه git اجرا می‌شود؟
