### ISSUE TITLE
عدم به روز رسانی اعلان در گوشی honor 8c

### ISSUE THREAD

**Issue by parse26** [persian-calendar/persian-calendar#921]
با سلام. اعلانات در گوشی honor 8c هووایی به روزرسانی نمیشود و باید یک بار به برنامه وارد شوی و خارج شوید تا اعلان تقویم بروز گردد و یا اینکه اعلانات کلا نمایش داده نمیشود خواهشمندیم این باگ را برطرف کنید. باتشکر🙏🌹

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را لطفاً بررسی فرمایید، ممنونم 🙏
