### ISSUE TITLE
تقویم قمری اشتباه است

### ISSUE THREAD

**Issue by 11Naweed11** [persian-calendar/persian-calendar#946]
سلام احترامات تقدیم است.
آقای محترم تقویم شما تاریخ قمری را یک روز بیشتر میگوید. امروز ۱۲ است اما در تقویم شما ۱۳ نوشته است. لطفاً اصلاح کنید. سپاس

**Comment by ebraminio** [comment]
سلام گرامی مطمئنید؟ شخص دیگری چنین چیزی را گزارش نکرده است، آیا مناسبت‌های ایران را فعال دارید؟ ممنون :)
