### ISSUE TITLE
چطوری باید قسمتی ازتقویم را در پروژه ای دیگر استفاده کنیم ؟

### ISSUE THREAD

**Issue by graceful1372** [persian-calendar/persian-calendar#950]
به عنوان یک تازه وارد نمی تونم فقط یه قسمت تقویم در پروژه خودم استفاده کنم
لطفا راهنمایی کنید

**Comment by ebraminio** [comment]
اگه پروژه اوپن‌سورس نیست کمی از نظر مجوزی دشواری دارد که در صفحهٔ اول برنامه توضیح داده شده، بهترین کار این است که سورس را مانند یک کتاب آموزشی ببینید و از آن یاد بگیرید ولی کپی نکنید عوضش بهترش را خودتان از ذهنتان انجام دهید، شما توانایی بیش از این را هم دارید، ممنون :)
