### ISSUE TITLE
دریافت مناسبتهای تقویم

### ISSUE THREAD

**Issue by martyr72** [persian-calendar/persian-calendar#954]
به نام خدا
با سلام و احترام
از شما درخواست دارم، مناسبتهای تقویم را در قالب فایلی در اختیارم قرار دهید.
با تشکر
@alirezaafkar 
@ebraminio 
@Arasteh

**Comment by ebraminio** [comment]
https://github.com/persian-calendar/persian-calendar/tree/main/PersianCalendar/data

سلام اینجا قرار دارد البته مطمئن شوید اول و خصوصاُ آخر فایل را مشاهده کنید، ممنون :)
