### ISSUE TITLE
Failed to calculate the value of property 'namespace Gradle Error

### ISSUE THREAD

**Issue by sareban101** [persian-calendar/persian-calendar#976]
با خطای بالا موقع بیلد گرفتن مواجه میشم
کاتلین هم به آخرین نسخه آپدیت شده 
لطفا راهنمایی کنید

**Comment by ebraminio** [comment]
سلام گرامی مشکل عجیبی است تا به حال ندیده‌ام، اگر به نتیجه‌ای رسیدید ما را مطلع کنید، ممنونم

**Comment by ebraminio** [comment]
حدس می‌زنم git در سیستمتان نصب نباشد، امکان دارد در cmd آزمایش کنید git باشد؟

**Comment by sareban101** [comment]
سلام
با clone از طریق git مشکل حل شد
با تشکر
