### ISSUE TITLE
اضافه کردن همه اذان‌ها در نوتیفیکشن‌بار

### ISSUE THREAD

**Issue by IamRezaMousavi** [persian-calendar/persian-calendar#979]
با سلام و احترام
خیلی دوست دارم برنامه شما رو جایگزین برنامه «بادصبا» کنم ولی قسمت نوتیفیکشن‌بار بادصبا (مخصوصا قسمت اذان‌ها که ساعات اذان همان روز بصورت کامل در نوتیفیکیشن میاد) خیلی برام کاربردی هستش

چندتا درخواست در این رابطه دارم:
۱.اضافه کردن بقیه اذان‌ها در نوتیفیکشن‌بار
۲.جدا کردن نوتیفیکشن تاریخِ روز، مناسبتِ روز و اذانِ روز به سه نوتیفیکشن جدا (که لازم نباشه برای دیدن کل اطلاعات بر روی نوتیفیکشن‌بار ضربه بزنیم)
۳.افزودن قابلیت تغییر سایز فونت نوتیفیکشن‌بار (این سایز فونت برای پدر و مادر قابل دیدن نیست و من تمایل دارم اونا رو به استفاده از برنامه‌های اپن سورس عادت بدم که متاسفانه در این مورد موفق نخواهم بود)

باتشکر از شما

**Comment by ebraminio** [comment]
سلام کرامی، موارد جالبی را مطرح کردید ممنونم، در رابطه با مورد سوم، تنظيمات font scaling گوشی آیا تآثیر مناسبی بر روی اندازهٔ متن اعلان نخواهد گذاشت؟ ممنونم

**Comment by IamRezaMousavi** [comment]
راه‌حلی که دادین خوب کار کرد

ولی در کل پیشنهاد میکنم روی ui/ux نوتیفیکیشن‌بار کار کنید و اون دو مورد بالا رو هم اضافه کنید

(ای کاش خودم بلد بودم و پول ریکوئست میفرستادم ولی فعلا فقط میتونم پیشنهاد بدم و خدا خدا کنم زودتر انجامش بدین)

از زحماتتون هم ممنونم
