### ISSUE TITLE
اشکال در روز امروز

### ISSUE THREAD

**Issue by AminSBU** [persian-calendar/persian-calendar#981]
سلام.
تو قسمت نوتیفیکیشن ها تاریخ امروز را تاریخ دیروز نشون میده. وقتی وارد برنامه میشیم درست میشه.

**Comment by ebraminio** [comment]
سلام گرامی https://dontkillmyapp.com را مشاهده کنید که راه‌حل‌هایی هم در اختیار قرار داده است، ممنونم 🙏
