### ISSUE TITLE
اشتباه در مناسبت های جهانی

### ISSUE THREAD

**Issue by mb-real** [persian-calendar/persian-calendar#985]
روز 18 مهر برابر با ۱۰ اکتبر به اشتباه روز جهانی حقوق بشر نوشته شده و فقط ۱۰ دسامبر صحیح است لطفاً مناسبت های جهانی را همیشه با ویکی پدیا چک کنید.

**Comment by ebraminio** [comment]
ممنونم :)

**Comment by ebraminio** [comment]
اسمتون رو هم https://github.com/persian-calendar/persian-calendar/commit/2695fc8d9996d12f3b4eac8daadc14c58d3b4520 اضافه کردم :)
