### ISSUE TITLE
Incorrect date in some hours of day

### ISSUE THREAD

**Issue by sadeq-n-yazdi** [persian-calendar/persian-calendar#987]
It seems the base day for calculation of current date is based on the **Iran Time zone** that causes a wrong date in some hours when you're in other timezones. For example in the GMT timezone it shows the next day's date after 20:00.

**Comment by ebraminio** [comment]
در ایمیل در این رابطه صحبت کردیم منتظر پاسختان آنجا هستم، ممنون :)
