### ISSUE TITLE
کنترل فیلدهای نوتیفیکیشن

### ISSUE THREAD

**Issue by khoshghalb2c** [persian-calendar/persian-calendar#988]
سلام،
بسیار ممنون از برنامه خوبتون.

من از قابلیت `نوتیفیکشن` استفاده می کنم، اما میخواهم در `نوتیفیکشن` فقط **تاریخ** و **مانده تا اذان بعدی** یا **اوقات شرعی** را داشته باشم نه مناسبت ها؛ _(ولی میخواهم در برنامه، تعطیلات، مناسبت‌های ایران، ایران‌باستان و مناسبت‌های بین‌المللی باشد)_

ممنون میشم اگر در تنظیمات، گزینه‌ای به منظور Customize Notification داشته باشید🙏🏻

**Comment by ebraminio** [comment]
سلام گرامی تعدادی گزینه در آخرین گزینهٔ تنظیمات، برگهٔ شخصی‌سازی ویجت وجود دارد  

<img width="460" alt="image" src="https://user-images.githubusercontent.com/833473/196673152-bce897c8-1345-490c-aa88-69b2c10d4c55.png">

که گزینهٔ دوم به نظر به آنکه شما فرمودید ارتباط دارد، در صورت امکان بررسی کنید، ممنون :)
